import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {PDFDocument} from 'pdf-lib';
import {createBankDebtService} from '../services/bank-debt.service.mjs';
import {createLawyerQueueService} from '../services/lawyer-queue.service.mjs';
import {debtHash} from '../services/bank-debt-pdf.mjs';
import {debtClaimant,debtDetails,debtParse} from '../services/bank-debt-domain.mjs';
const owner={tenantId:1,user:{id:101,tenant_id:1,role:'member',email:'cliente@example.test'}},admin={tenantId:1,user:{id:102,role:'super_admin'}},stranger={tenantId:2,user:{id:103,role:'member'}};
const details={creditor:'Banco de Teste',kind:'overdraft',since:'2025-03-01',originalCents:1000000,chargedCents:4000000,offeredCents:1200000,description:'Notificações recebidas por e-mail. Dados fictícios.',consent:true};
const claimant={fullName:'Cliente de Teste',document:'52998224725',email:'cliente@example.test',phone:'11999999999',nationality:'Brasileiro',maritalStatus:'Solteiro',profession:'Professor',street:'Rua de Teste',number:'10',complement:'',neighborhood:'Centro',city:'Jundiaí',uf:'SP',postalCode:'13201000'};
const review={reviewedCents:1500000,priceCents:19900,methodology:'Cálculo fictício para teste: principal R$ 10.000 e encargos documentados R$ 5.000. Não utilizar em caso real.',legalBasis:'Fundamentação fictícia para teste de geração documental. Não protocolar este atendimento.',creditorLegalName:'Banco de Teste SA',creditorDocument:'00000000000000',creditorAddress:'Endereço fictício, SP',lawyerUserId:104,lawyerName:'Advogado de Teste',lawyerOab:'SP 000000',confirmed:true};
test('dívida: validações e fluxo persistente de análise, pagamento, assinatura, PDF e advogado',async()=>{
  const pg=new PGlite();try{
    await pg.exec((await readFile(new URL('../db/schema.sql',import.meta.url),'utf8')).replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
    await pg.exec(await readFile(new URL('../db/bank-debt.sql',import.meta.url),'utf8'));
    await pg.exec("INSERT INTO audita_users(id,tenant_id,email,name,role,password_hash) VALUES (101,1,'cliente@example.test','Cliente','member','test'),(102,1,'admin@example.test','Admin','super_admin','test'),(104,1,'adv@example.test','Advogado','lawyer','test')");
    const pool={query:(...a)=>pg.query(...a),connect:async()=>({query:(...a)=>pg.query(...a),release(){}})},getDb=()=>({pool,dbReady:true});
    let calls=0;const checkout=async(auth,p)=>{calls++;return {id:'cs_test_debt',url:'https://checkout.stripe.com/test',expiresAt:Math.floor(Date.now()/1000)+1800}};
    let service=createBankDebtService({getDb,checkout}),c=await service.create(owner);
    const action=async(type,extra={},auth=owner)=>{c=await service.command(auth,c.id,{revision:c.revision,action:type,...extra},{ip:'127.0.0.1',userAgent:'Automated local test'});return c};
    await assert.rejects(service.get(stranger,c.id),{status:404});
    await assert.rejects(service.createCheckout(owner,c.id,{}),{status:409});
    await assert.rejects(action('answer',{key:'excessive',value:true}),{status:422});
    for(const key of ['open','notified','excessive'])await action('answer',{key,value:true});
    assert.equal(c.status,'details');
    assert.throws(()=>debtParse(debtDetails,{...details,since:'2025-02-30'}));
    assert.throws(()=>debtParse(debtDetails,{...details,originalCents:-1}));
    assert.throws(()=>debtParse(debtClaimant,{...claimant,document:'11111111111'}));
    await action('details',{details});assert.equal(c.status,'calculation_pending');assert.equal(c.review,null);
    await assert.rejects(action('review',{review}),{status:403});
    await assert.rejects(action('review',{review},admin),{status:422});
    const pdf=await PDFDocument.create();pdf.addPage();const bytes=Buffer.from(await pdf.save());
    c=await service.upload(owner,c.id,{bytes,name:'cobranca.pdf',kind:'evidence'});
    await assert.rejects(service.upload(owner,c.id,{bytes:Buffer.from('<script>'),name:'x.pdf',kind:'evidence'}),{status:422});
    await action('review',{review},admin);assert.equal(c.status,'offer');
    await assert.rejects(service.createCheckout(owner,c.id,{accepted:false,reviewId:c.review.id}),{status:422});
    const session=await service.createCheckout(owner,c.id,{accepted:true,reviewId:c.review.id});
    await service.createCheckout(owner,c.id,{accepted:true,reviewId:c.review.id});assert.equal(calls,1);
    c=await service.get(owner,c.id);assert.equal(c.status,'payment_pending');
    await assert.rejects(action('claimant',{claimant,conciliation:true}),{status:409});
    const event={id:'evt_debt',type:'checkout.session.completed',data:{object:{id:session.id,payment_status:'unpaid',currency:'brl',amount_total:19900,metadata:{purchase_kind:'bank_debt',debt_case_id:c.id,debt_review_id:c.review.id,audita_user_id:'101',audita_tenant_id:'1'}}}};
    await service.paymentEvent(event);c=await service.get(owner,c.id);assert.equal(c.status,'payment_pending');
    await assert.rejects(service.createCheckout(owner,c.id,{accepted:true,reviewId:c.review.id}),{status:409});
    event.id='evt_wrong';event.data.object.payment_status='paid';event.data.object.amount_total=1;
    await assert.rejects(service.paymentEvent(event),{status:409});
    event.id='evt_paid';event.type='checkout.session.async_payment_succeeded';event.data.object.amount_total=19900;
    await service.paymentEvent(event);assert.deepEqual(await service.paymentEvent(event),{duplicate:true});
    service=createBankDebtService({getDb,checkout});c=await service.get(owner,c.id);assert.equal(c.status,'paid');
    await action('claimant',{claimant,conciliation:true});
    await assert.rejects(action('sign',{accepted:true,name:claimant.fullName,version:c.version,termsHash:'wrong'}),{status:422});
    await action('sign',{accepted:true,name:claimant.fullName,version:c.version,termsHash:debtHash(JSON.stringify(c.legalTexts))});
    await assert.rejects(action('submit'),{status:422});
    for(const kind of ['identity','address'])c=await service.upload(owner,c.id,{bytes,name:kind+'.pdf',kind});
    await action('submit');assert.equal(c.status,'submitted');const job=c.jobId;
    await action('submit');assert.equal(c.jobId,job);assert.equal((await pg.query('SELECT count(*)::int AS n FROM audita_lawyer_jobs')).rows[0].n,1);
    const file=await service.download(owner,c.id,'report');assert.ok((await PDFDocument.load(file.bytes)).getPageCount()>=3);
    await assert.rejects(service.download(stranger,c.id,'report'),{status:404});
    const queue=createLawyerQueueService({getDb}),lawyer={id:104,role:'lawyer'};
    assert.equal((await queue.list(lawyer))[0].module_label,'Dívidas Bancárias Abusivas');
    assert.equal((await queue.list({id:999,role:'lawyer'})).length,0);
    await assert.rejects(queue.claim({id:999,role:'lawyer'},job),{status:409});
    await assert.rejects(queue.document(lawyer,job,'report'),{status:404});
    await queue.claim(lawyer,job);await queue.complete(lawyer,job,'TESTE-12345');
    assert.equal((await service.get(owner,c.id)).job.protocol_number,'TESTE-12345');
    const rejected=await service.create(owner);const no=await service.command(owner,rejected.id,{revision:0,action:'answer',key:'open',value:false});assert.equal(no.status,'not_eligible');
  }finally{await pg.close();}
});
