const root=document.querySelector('#dividas-bancarias');
const $=s=>root.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)/100);
const currencyCents=value=>Number(String(value).replace(/\D/g,''));
function maskCurrency(input){const digits=input.value.replace(/\D/g,'');input.value=digits?money(Number(digits)):'';const cents=currencyCents(input.value);input.setCustomValidity(digits&&(cents<Number(input.dataset.minCents)||cents>10000000000)?'Informe um valor entre '+money(input.dataset.minCents)+' e '+money(10000000000)+'.':'');}
const questions=[['open','Você tem alguma dívida bancária em aberto?','Sim, tenho uma dívida em aberto','Não tenho dívida em aberto'],['notified','Você está recebendo notificações de cobrança dessa dívida?','Sim, estou recebendo cobranças','Ainda não recebi cobranças'],['excessive','Você considera que os juros cobrados estão muito acima do valor que ficou em aberto?','Sim, o valor aumentou muito','Não / não tenho certeza']];
const statuses={triage:'Triagem',not_eligible:'Fora do foco inicial',details:'Detalhes da dívida',calculation_pending:'Aguardando cálculo',offer:'Contratação disponível',payment_pending:'Pagamento pendente',paid:'Cadastro',signature:'Documentos e assinatura',submitted:'Com o advogado'};
const ufs='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');
let current=null,config=null,busy=false,edit=false,initialized=false,poll;
async function api(path,options={}){const res=await fetch('/api/bank-debt'+path,{...options,headers:{...(typeof options.body==='string'?{'content-type':'application/json'}:{}),...options.headers}});const data=await res.json();if(!res.ok)throw Object.assign(new Error(data.message||'Não foi possível continuar.'),{status:res.status});return data;}
const post=(path,body={})=>api(path,{method:'POST',body:JSON.stringify(body)});
function error(message=''){$('#debtError').hidden=!message;$('#debtError').textContent=message;}
async function run(fn){if(busy)return;busy=true;error();root.setAttribute('aria-busy','true');root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){error(e.message);if(e.status===409&&current)await load(current.id).catch(()=>{});}finally{busy=false;root.setAttribute('aria-busy','false');root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const button=(action,label)=>`<div class="charge-analysis-actions"><button type="button" data-debt="${action}">${label}</button></div>`;
const field=(name,label,value='',type='text',extra='')=>type==='number'?`<label>${label}<input name="${name}" type="text" inputmode="numeric" data-currency data-min-cents="${Math.round(Number(extra.match(/min="([^"]+)"/)?.[1]||0)*100)}" value="${esc(value===''?'':money(Math.round(Number(value)*100)))}" placeholder="R$ 0,00" required></label>`:`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required ${extra}></label>`;
const area=(name,label,value='',extra='')=>`<label>${label}<textarea name="${name}" rows="4" ${extra}>${esc(value)}</textarea></label>`;
const select=(name,label,choices,value)=>`<label>${label}<select name="${name}" required>${choices.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select></label>`;
const bubble=html=>`<div class="charge-analysis-message assistant"><span class="charge-analysis-avatar" aria-hidden="true"><img src="/assets/audita-profile-assistant.png" alt=""></span><div class="charge-analysis-bubble">${html}</div></div>`;
const form=(id,html,label)=>`<form data-form="${id}" class="debt-form">${html}<div class="charge-analysis-actions"><button type="submit">${label}</button></div></form>`;
function detailsForm(){const d=current.details||{};return form('details',
  field('creditor','Qual banco ou cobrador está pedindo o pagamento?',d.creditor||'','text','maxlength="300"')+
  select('kind','Qual é o tipo de dívida?',[['overdraft','Cheque especial'],['card','Cartão de crédito'],['loan','Empréstimo'],['financing','Financiamento em atraso'],['other','Outra dívida bancária']],d.kind)+
  field('since','Desde quando a dívida está em aberto?',d.since||'','date',`max="${new Date().toISOString().slice(0,10)}"`)+
  field('original','Quanto ficou em aberto originalmente (R$)?',d.originalCents?d.originalCents/100:'','number','min="0.01" max="100000000" step="0.01"')+
  field('charged','Quanto estão cobrando agora (R$)?',d.chargedCents?d.chargedCents/100:'','number','min="0.01" max="100000000" step="0.01"')+
  field('offered','Quanto você gostaria de propor para pagar (R$)?',d.offeredCents!=null?d.offeredCents/100:'','number','min="0" max="100000000" step="0.01"')+
  '<p class="debt-note">Sua proposta é uma preferência pessoal. O cálculo Audita será apresentado separadamente.</p>'+
  '<label class="debt-check"><input type="checkbox" name="consent" required> Autorizo a análise destes dados e documentos pela Audita e pela equipe responsável.</label>','Enviar para análise');}

function paymentRow(p={}){return `<div data-payment>${field('paymentDate','Data do pagamento',p.date||'','date')}${field('paymentAmount','Valor pago (R$)',p.amountCents!=null?p.amountCents/100:'','number','min="0.01"')}<div class="charge-analysis-actions"><button type="button" data-debt="remove-payment">Remover pagamento</button></div></div>`;}
function estimateForm(){
 const d=current.details,s=current.estimate?.scenario||{},choices={overdraft:[['overdraft','Pessoa física — cheque especial']],loan:[['loan','Pessoa física — crédito pessoal não consignado']],card:[['revolving','Pessoa física — cartão rotativo']],financing:[['vehicle','Pessoa física — aquisição de veículos']]}[d.kind];
 if(!choices)return '<p>A modalidade informada exige revisão manual. Anexe os documentos para a equipe analisar.</p>';
 return '<details '+(current.estimate?'':'open')+'><summary>'+ (current.estimate?'Refazer estimativa':'Estimar com a taxa do Banco Central')+'</summary><p>Confirme a modalidade exata. Contratos de pessoa jurídica, consignados, cartão parcelado e outros financiamentos seguem para análise manual.</p>'+form('estimate',
 select('modality','Modalidade para comparação',choices,s.modality)+field('contractDate','Data da contratação',s.contractDate||'','date')+
 field('baseDate','Data do saldo inicial da simulação',s.baseDate||d.since,'date')+field('base','Saldo em aberto nessa data (R$)',s.baseCents!=null?s.baseCents/100:d.originalCents/100,'number','min="0.01"')+
 field('asOf','Data da cobrança atual informada',s.asOf||'','date')+
 '<label>Taxa de juros do contrato (% ao mês, opcional — não informe o CET)<input name="contractRate" type="number" inputmode="decimal" step="0.0001" min="0" max="100" value="'+esc(s.contractMonthlyRate??'')+'"></label>'+
 select('capitalization','Premissa de juros para esta simulação',[['compound','Compostos — equivalência diária'],['simple','Simples — sobre principal remanescente']],s.capitalization||'compound')+
 '<p class="debt-note">Usaremos dias corridos/30. A equipe confirmará essa premissa no contrato; não é uma conclusão sobre a capitalização permitida.</p><p>Pagamentos entre a data inicial e a cobrança (se não houve, deixe sem pagamentos).</p><div data-payments>'+ (s.payments||[]).map(paymentRow).join('')+'</div>'+button('add-payment','Adicionar pagamento')+
 '<label class="debt-check"><input type="checkbox" name="confirmed" required> Confirmo a modalidade, as datas, todos os pagamentos e que não houve novos saques ou compras neste período. Entendo que esta é uma estimativa sem acrescentar multa, mora, tarifas, seguros, IOF ou correção monetária.</label>','Calcular estimativa')+'</details>';
}
function estimateResult(){const e=current.estimate;if(!e)return '';const rate=v=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:4});return `<section class="debt-result"><p>ESTIMATIVA PRELIMINAR · AGUARDA VALIDAÇÃO</p><h3>Saldo estimado pela referência BACEN</h3><strong>${money(e.revised.balanceCents)}</strong><p>Diferença estimada para análise: <b>${money(e.differenceCents)}</b></p><p>Taxa BACEN: ${rate(e.rate.monthlyPercent)}% ao mês · ${e.rate.month} · SGS ${e.rate.code}.</p>${e.rateDifferencePoints!==null?`<p>Taxa contratada informada: ${rate(e.scenario.contractMonthlyRate)}% ao mês. Diferença: ${rate(e.rateDifferencePoints)} pontos percentuais.</p>`:'<p>Taxa contratada não informada; não foi feita comparação entre taxas.</p>'}${e.differenceCents===0?'<p>Este cenário não identificou diferença positiva frente à cobrança informada.</p>':''}<p>O resultado não comprova abusividade nem garante redução. A equipe precisa revisar antes de liberar a contratação.</p><details><summary>Ver premissas e memória de cálculo</summary><p class="debt-pre">${esc(current.estimateText)}</p><a href="${esc(e.rate.url)}" target="_blank" rel="noopener">Consultar dado oficial do Banco Central</a></details></section>`;}

function uploads(){return `<section class="debt-documents"><h3>Documentos do atendimento</h3><ul>${(current.documents||[]).map(d=>`<li><a href="/api/bank-debt/cases/${current.id}/documents/${d.id}">${esc(d.name)}</a> <small>${esc({evidence:'Cobrança',identity:'Identificação',address:'Residência'}[d.kind])}</small></li>`).join('')||'<li>Nenhum documento enviado.</li>'}</ul>${current.owner&&['calculation_pending','paid','signature'].includes(current.status)?form('upload',select('kind','Que documento você vai enviar?',current.status==='calculation_pending'?[['evidence','Extrato, contrato ou notificação de cobrança']]:[['identity','Documento de identificação'],['address','Comprovante de residência'],['evidence','Extrato, contrato ou notificação de cobrança']])+`<label>Arquivo PDF, PNG ou JPG (até 10 MB)<input type="file" name="file" required accept="application/pdf,image/png,image/jpeg"></label>`,'Anexar documento'):''}</section>`;}
function summary(){const d=current.details;return d?`<dl class="debt-summary"><div><dt>Banco / cobrador</dt><dd>${esc(d.creditor)}</dd></div><div><dt>Dívida original informada</dt><dd>${money(d.originalCents)}</dd></div><div><dt>Cobrança atual</dt><dd>${money(d.chargedCents)}</dd></div><div><dt>Sua proposta pessoal</dt><dd>${money(d.offeredCents)}</dd></div></dl>`:'';}
function reviewer(){if(!current.operator||!['calculation_pending','offer'].includes(current.status))return '';const r=current.review||{};return `<details class="debt-review"><summary>Equipe Audita · publicar análise validada</summary><p>A estimativa BACEN é preliminar. Confira contrato, histórico, encargos e fundamentação antes de publicar a análise validada que libera a contratação.</p>${form('review',field('reviewed','Saldo recalculado (R$)',r.reviewedCents!=null?r.reviewedCents/100:'','number','min="0" step="0.01" max="100000000"')+field('price','Preço do serviço (R$)',r.priceCents?r.priceCents/100:'','number','min="1" step="0.01" max="100000000"')+area('methodology','Memória de cálculo: períodos, taxas, valores e fontes',r.methodology||current.estimateText||'','required minlength="30" maxlength="12000"')+area('legalBasis','Fundamentação jurídica específica revisada',r.legalBasis||'','required minlength="30" maxlength="12000"')+field('creditorLegalName','Razão social do credor',r.creditorLegalName||'')+field('creditorDocument','CNPJ do credor (14 dígitos)',r.creditorDocument||'','text','pattern="[0-9]{14}"')+field('creditorAddress','Endereço do credor',r.creditorAddress||'')+field('lawyerName','Nome do advogado outorgado',r.lawyerName||'')+field('lawyerOab','OAB e UF do advogado',r.lawyerOab||'')+'<label class="debt-check"><input name="confirmed" type="checkbox" required> Confirmei documentos, cálculo, fundamentação e condições do serviço.</label>','Publicar análise e contratação')}</details>`;}
function claimantForm(){const c=current.claimant||{};return form('claimant',field('fullName','Nome completo',c.fullName||'')+field('document','CPF',c.document||'')+field('email','E-mail',c.email||'','email')+field('phone','Telefone',c.phone||'','tel')+field('nationality','Nacionalidade',c.nationality||'Brasileiro(a)')+field('maritalStatus','Estado civil',c.maritalStatus||'')+field('profession','Profissão',c.profession||'')+field('postalCode','CEP',c.postalCode||'','text','pattern="[0-9]{5}-?[0-9]{3}"')+field('street','Rua / avenida',c.street||'')+field('number','Número',c.number||'')+`<label>Complemento (opcional)<input name="complement" value="${esc(c.complement)}" maxlength="200"></label>`+field('neighborhood','Bairro',c.neighborhood||'')+field('city','Cidade',c.city||'')+select('uf','Estado',ufs.map(v=>[v,v]),c.uf||'SP')+'<label class="debt-check"><input type="checkbox" name="conciliation" required> Tenho interesse na tentativa de conciliação com o credor.</label>','Conferir procuração e contrato');}
function render(){
  const s=current?.status||'triage',step=({triage:0,not_eligible:0,details:1,calculation_pending:2,offer:3,payment_pending:3,paid:4,signature:5,submitted:6})[s];
  $('#debtProgress').innerHTML=['Triagem','Dívida','Análise','Contratação','Seus dados','Assinatura','Advogado'].map((label,i)=>`<li ${i===step?'aria-current="step"':''} class="${i<step?'done':''}"><span>${i<step?'✓':i+1}</span>${label}</li>`).join('');
  let html='';
  if(!current){html=bubble('<p>Olá! Sou a IA AUDITA. Vou conduzir uma verificação inicial da sua dívida bancária para entender as cobranças e os juros aplicados.</p><p>Vamos começar pela sua situação atual.</p><h2>Você tem alguma dívida bancária em aberto?</h2><div class="charge-analysis-actions"><button type="button" data-start-answer="true">Sim, tenho uma dívida em aberto</button><button type="button" data-start-answer="false">Não tenho dívida em aberto</button></div>'+'<p class="debt-note">A triagem não confirma abusividade nem garante redução da dívida.</p>');}
  else if(edit){html=bubble('<h2>Confira os dados da dívida</h2><p>Alterações exigem uma nova análise.</p>'+detailsForm()+button('cancel-edit','Cancelar',true));}
  else if(s==='triage'){
    html=questions.filter(q=>current.answers[q[0]]!==undefined).map(q=>bubble(`<p>${q[1]}</p>`)+`<div class="charge-analysis-message user"><div class="charge-analysis-bubble"><p>${current.answers[q[0]]?'Sim':'Não'}</p></div></div>`).join('');
    const q=questions.find(q=>current.answers[q[0]]===undefined);html+=bubble(`<h2 tabindex="-1" id="debtQuestion">${q[1]}</h2><div class="charge-analysis-actions"><button type="button" class="primary-action" data-answer="${q[0]}" data-value="true">${q[2]}</button><button type="button" class="secondary-action" data-answer="${q[0]}" data-value="false">${q[3]}</button></div>`);
  }else if(s==='not_eligible')html=bubble('<h2>Este atendimento tem um foco específico</h2><p>Por enquanto, analisamos dívidas bancárias em aberto, com notificações de cobrança e suspeita de juros excessivos. Suas respostas não atendem a todos esses critérios. Isso não significa que você não tenha direitos.</p>'+button('new','Recomeçar a triagem',true)+'<a class="secondary-action" href="#analise-cobrancas">Analisar cobranças indevidas do Itaú</a>');
  else if(s==='details')html=bubble('<h2>Vamos entender os valores</h2><p>Informe o que você sabe sobre a dívida. Vamos comparar a cobrança com os documentos.</p>'+detailsForm());
  else if(s==='calculation_pending')html=bubble('<h2>Recebi os detalhes. Vamos preparar sua análise.</h2><p>Você pode estimar o saldo pela taxa média do Banco Central. Anexe contrato, extratos e notificações para a equipe validar o resultado e liberar a contratação.</p>'+summary()+estimateResult()+(current.owner?estimateForm():'')+button('refresh','Consultar atualização')+(current.owner?button('edit','Corrigir os valores',true):'')+uploads()+reviewer());
  else if(['offer','payment_pending'].includes(s)){const r=current.review;html=bubble('<h2>Sua análise está disponível</h2>'+summary()+`<div class="debt-result"><span>Saldo recalculado pela Audita</span><strong>${money(r.reviewedCents)}</strong><p>Diferença em discussão: ${money(current.details.chargedCents-r.reviewedCents)}. Sujeita à avaliação jurídica e à decisão do caso.</p></div><details><summary>Entender o cálculo</summary><p class="debt-pre">${esc(r.methodology)}</p><p class="debt-pre">${esc(r.legalBasis)}</p></details><section class="debt-plan"><span>Seu plano de atendimento</span><h3>${money(r.priceCents)} <small>pagamento único</small></h3><ul><li>Análise e relatório da dívida</li><li>Preparação da petição e procuração</li><li>Assinatura eletrônica</li><li>Encaminhamento e acompanhamento pelo advogado</li></ul><p>${esc(current.terms)}</p>${current.owner?form('checkout',`<label class="debt-check"><input type="checkbox" name="accepted" required> Li a análise e aceito as condições do serviço.</label>`,s==='payment_pending'?'Retomar pagamento':'Contratar e continuar'):''}</section>`+(s==='payment_pending'?'<p>O avanço depende da confirmação do pagamento pela Stripe. Se você já pagou, consulte a atualização.</p>'+button('refresh','Verificar pagamento',true):current.owner?button('edit','Corrigir informações',true):'')+reviewer());}
  else if(s==='paid')html=bubble('<h2>Pagamento confirmado. Vamos preparar seus documentos.</h2><p>Precisamos dos seus dados para a petição e a procuração. O advogado fará o protocolo no tribunal do seu estado.</p>'+claimantForm()+uploads());
  else if(s==='signature'){html=bubble(`<h2>Confira e assine seus documentos</h2><p>Advogado indicado: ${esc(current.review.lawyerName)} · OAB ${esc(current.review.lawyerOab)}.</p><details open><summary>Procuração</summary><p class="debt-pre">${esc(current.legalTexts.powerOfAttorney)}</p></details><details><summary>Contrato do serviço</summary><p class="debt-pre">${esc(current.legalTexts.agreement)}</p></details>`+uploads()+(current.acceptance?`<p class="debt-success">Assinado por ${esc(current.acceptance.name)} em ${new Date(current.acceptance.at).toLocaleString('pt-BR')}.</p>`+button('submit','Concluir e enviar ao advogado'):form('sign',field('name','Digite seu nome completo para assinar',current.claimant.fullName)+'<label class="debt-check"><input name="accepted" type="checkbox" required> Li a procuração e o contrato e confirmo minha assinatura eletrônica.</label>','Assinar digitalmente'))+`<details><summary>Corrigir meus dados</summary><p>Após alterar, será necessário assinar novamente.</p>${claimantForm()}</details>`);}
  else if(s==='submitted')html=bubble(`<p class="debt-eyebrow">SOLICITAÇÃO CONCLUÍDA</p><h2>${current.job?.status==='filed'?'Protocolo registrado pelo advogado':'Tudo pronto para o advogado responsável'}</h2><p>Sua solicitação está completa. O advogado responsável da Audita dará início ao protocolo da sua petição no tribunal da sua região.</p><p>${current.job?.status==='filed'?`Protocolo: <strong>${esc(current.job.protocol_number)}</strong>`:current.job?.status==='claimed'?'O advogado já assumiu seu atendimento.':'Seu atendimento está na fila do advogado.'}</p><div class="charge-analysis-actions">${[['report','Baixar petição completa'],['powerOfAttorney','Baixar procuração'],['agreement','Baixar contrato']].map(([key,label])=>`<a class="secondary-action" href="/api/bank-debt/cases/${current.id}/documents/${key}">${label}</a>`).join('')}</div>${button('refresh','Atualizar acompanhamento',true)}`);
  $('#debtStage').innerHTML=html;
  const reviewForm=$('#debtStage form[data-form=review]');if(reviewForm)reviewForm.insertAdjacentHTML('afterbegin',select('lawyerUserId','Advogado responsável cadastrado',(config?.lawyers||[]).map(u=>[String(u.id),esc(u.name)]),String(current.review?.lawyerUserId||'')));
  if(current&&!current.owner)$('#debtStage').querySelectorAll('form:not([data-form="review"]),[data-debt="submit"],[data-answer]').forEach(e=>e.hidden=true);
  schedulePaymentCheck();
}
function schedulePaymentCheck(){clearTimeout(poll);if(current?.status!=='payment_pending'||document.body.dataset.activePage!=='dividas-bancarias')return;poll=setTimeout(async()=>{try{if(!busy){const fresh=(await api('/cases/'+current.id)).case;if(fresh.revision!==current.revision){current=fresh;render();await refreshList();}}}catch{}finally{schedulePaymentCheck();}},10000);}
async function refreshList(){const cases=config?.authenticated&&config.ready?(await api('/cases')).cases:[];$('#debtCases').innerHTML=cases.map(c=>`<button type="button" data-case="${c.id}" class="${c.id===current?.id?'selected':''}"><strong>${esc(c.creditor||'Nova análise')}</strong><small>${statuses[c.status]} · ${new Date(c.updated_at).toLocaleDateString('pt-BR')}</small></button>`).join('')||'<p>Nenhum atendimento salvo.</p>';}
async function load(id){current=(await api('/cases/'+id)).case;edit=false;const url=new URL(location.href);url.searchParams.set('debt_case',id);history.replaceState(null,'',url);render();await refreshList();}
async function command(action,extra={}){current=(await post(`/cases/${current.id}/actions`,{action,revision:current.revision,...extra})).case;edit=false;render();await refreshList();$('#debtQuestion')?.focus();}
async function start(){if(!config?.authenticated){document.querySelector('#loginButton')?.click();return;}current=(await post('/cases')).case;await load(current.id);}
root.addEventListener('input',e=>{if(e.target.matches('[data-currency]'))maskCurrency(e.target);});
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.startAnswer!==undefined){run(async()=>{await start();if(current)await command('answer',{key:'open',value:b.dataset.startAnswer==='true'});});return;}
  if(b.dataset.case){run(()=>load(b.dataset.case));return;}
  if(b.dataset.answer){run(()=>command('answer',{key:b.dataset.answer,value:b.dataset.value==='true'}));return;}
  const action=b.dataset.debt;
  if(action==='add-payment'){const list=$('[data-payments]');if(list.children.length<120)list.insertAdjacentHTML('beforeend',paymentRow());return;}
  if(action==='remove-payment'){b.closest('[data-payment]').remove();return;}
  if(action==='start'||action==='new')run(start);
  if(action==='refresh'&&current)run(()=>load(current.id));
  if(action==='edit'){edit=true;render();}
  if(action==='cancel-edit'){edit=false;render();}
  if(action==='submit')run(()=>command('submit'));
  if(action==='help')error('Responda às perguntas, informe a dívida e anexe as cobranças. A contratação é liberada após a análise. Depois do pagamento, você preenche seus dados e assina. O advogado recebe os documentos para revisar e protocolar.');
});
root.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();run(async()=>{const d=new FormData(f),v=Object.fromEntries(d),cents=k=>currencyCents(v[k]);
  if(f.dataset.form==='estimate')await command('estimate',{scenario:{modality:v.modality,contractDate:v.contractDate,baseDate:v.baseDate,asOf:v.asOf,baseCents:cents('base'),contractMonthlyRate:v.contractRate===''?null:Number(v.contractRate),capitalization:v.capitalization,payments:[...f.querySelectorAll('[data-payment]')].map(row=>({date:row.querySelector('[name=paymentDate]').value,amountCents:currencyCents(row.querySelector('[name=paymentAmount]').value)})),confirmed:d.has('confirmed')}});
  if(f.dataset.form==='details')await command('details',{details:{creditor:v.creditor,kind:v.kind,since:v.since,originalCents:cents('original'),chargedCents:cents('charged'),offeredCents:cents('offered'),description:current.details?.description||'',consent:d.has('consent')}});
  if(f.dataset.form==='review'){v.lawyerUserId=Number(v.lawyerUserId);const reviewedCents=cents('reviewed'),priceCents=cents('price');delete v.reviewed;delete v.price;await command('review',{review:{...v,reviewedCents,priceCents,confirmed:d.has('confirmed')}});}
  if(f.dataset.form==='claimant'){delete v.conciliation;await command('claimant',{claimant:v,conciliation:d.has('conciliation')});}
  if(f.dataset.form==='sign')await command('sign',{name:v.name,accepted:d.has('accepted'),version:current.version,termsHash:current.termsHash});
  if(f.dataset.form==='upload'){const file=d.get('file');if(file.size>10*1024*1024)throw new Error('O arquivo excede 10 MB.');current=(await api(`/cases/${current.id}/documents?kind=${encodeURIComponent(v.kind)}&name=${encodeURIComponent(file.name)}`,{method:'POST',body:file,headers:{'content-type':'application/octet-stream'}})).case;render();}
  if(f.dataset.form==='checkout'){const r=await post(`/cases/${current.id}/checkout`,{accepted:d.has('accepted'),reviewId:current.review.id});const url=new URL(r.url);if(url.protocol!=='https:')throw new Error('Endereço de pagamento inválido.');location.assign(url.href);}
});});
async function init(){config=await api('/config');const id=new URLSearchParams(location.search).get('debt_case');if(config.authenticated&&config.ready&&id)await load(id);else{current=null;render();await refreshList();}}
function activate(){if(document.body.dataset.activePage!=='dividas-bancarias'){clearTimeout(poll);return;}if(!initialized){initialized=true;run(async()=>{try{await init();}catch(e){initialized=false;throw e;}});}else render();}
document.addEventListener('audita:pagechange',activate);
window.addEventListener('audita:auth-changed',()=>{clearTimeout(poll);current=null;config=null;initialized=false;render();activate();});
render();activate();
