import {createAuditaChatMotion} from './audita-chat-motion.js';
const root=document.querySelector('#glosasApp');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const categories={administrative:'Administrativa',financial:'Financeira',clinical:'Clínica',unknown:'A conferir'};
const labels={billed:'Faturado',paid:'Pago',denied:'Glosado',unreconciled:'Não conciliado'};
let current=null,cases=[],user=null,ready=false,aiReady=false,busy=false,error='',epoch=0,dirty=false,step='intro',itemIndex=0;
const fresh=()=>({operator:'',lot:'',consent:false,items:[]});
let draft=fresh();
const motion=createAuditaChatMotion({getStage:()=>root.querySelector('.glosas-stage'),getConversation:()=>root.querySelector('.charge-analysis-conversation'),isActive:()=>document.body.dataset.activePage==='auditoria-glosas'});
async function api(path,method='GET',data){const turn=epoch;const res=await fetch('/api/glosas'+path,{method,credentials:'same-origin',headers:data?{'content-type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const result=await res.json();if(turn!==epoch)throw Error('Sessão alterada.');if(!res.ok)throw Error(result.message||'Não foi possível continuar.');return result;}
const field=(key,label,value='',extra='')=>`<label>${label}<input name="${key}" value="${esc(value)}" ${extra}></label>`;
const button=(action,label,extra='')=>`<button type="button" class="secondary-action" data-glosas="${action}" ${extra}>${label}</button>`;
const question=text=>`<h3 class="glosas-question" tabindex="-1">${text}</h3>`;
const assistant=html=>`<div class="charge-analysis-message assistant"><span class="charge-analysis-avatar-anchor" aria-hidden="true"></span><div class="charge-analysis-bubble">${html}</div></div>`;
const reply=text=>`<div class="charge-analysis-message user"><div class="charge-analysis-bubble">${esc(text)}</div></div>`;
function intro(){return assistant(`<h3>Vamos analisar as glosas do seu faturamento?</h3><p>Olá! Sou a IA AUDITA. Envie o demonstrativo de glosas e, se disponíveis, o faturamento, contrato e autorizações. Vou extrair os itens, cruzar valores e apontar divergências com as referências dos documentos.</p><p>Você confere os dados extraídos antes de gerar o relatório e as minutas. As sugestões não substituem revisão profissional e nenhum recurso é enviado automaticamente.</p>${question('Podemos começar?')}<div class="glosas-choices">${button('start','Sim, vamos conferir minhas glosas')}</div>`);}
const docTypes={denial:'Demonstrativo de glosas',billing:'Faturamento enviado',contract:'Contrato',authorization:'Autorização'};
function documentForm(){return `${question(current?'Quais documentos vamos analisar?':'Antes de enviar os documentos')}<p>Use arquivos anonimizados. Não envie nomes, CPF, carteirinhas ou prontuários completos. PDF: até 20 páginas e 10 MB. XML UTF-8: até 250 KB. Até 4 arquivos, 20 MB e 40 páginas por lote.</p>${!current?`<form data-step="create"><label class="glosas-consent"><input type="checkbox" name="aiConsent" required>Tenho autorização e base legal para enviar estes documentos e autorizo sua leitura pela OpenAI para esta análise.</label><button class="primary-action" type="submit">Continuar para os documentos</button></form>`:`<ul>${current.documents.map(d=>`<li>${esc(docTypes[d.type])}: <a href="/api/glosas/cases/${current.id}/documents/${d.id}">${esc(d.name)}</a> · ${d.pages?d.pages+' páginas':'XML'}</li>`).join('')}</ul>${current.documents.length<4?`<form data-step="upload"><label>Tipo de documento<select name="type">${Object.entries(docTypes).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Documento<input name="file" type="file" accept=".pdf,.xml,application/pdf,application/xml" required></label><button class="primary-action" type="submit">Enviar documento</button></form>`:''}<div class="glosas-toolbar">${button('extract','Ler e cruzar documentos',!aiReady||!current.documents.some(d=>d.type==='denial')?'disabled':'')}</div>${!aiReady?'<p class="glosas-status">A leitura por IA está indisponível: falta configurar a chave OpenAI neste ambiente. Seus documentos não foram enviados para análise.</p>':''}`}`;}
function extractionReview(){const x=current.automation.extraction;return `${question('Confira o que encontrei nos documentos')}<p>Campos em branco e divergências precisam de conferência. As referências foram extraídas por IA; confirme no documento original.</p>${x.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}<div class="glosas-review">${draft.items.map((v,i)=>`<div><p><strong>Item ${i+1}</strong> · Guia ${esc(v.guide||'não identificada')} · sequência ${esc(v.sequence||'não identificada')}</p><p>Faturado ${v.billed===null?'ausente':money(v.billed)} · pago ${v.paid===null?'ausente':money(v.paid)} · glosado ${v.denied===null?'ausente':money(v.denied)}</p>${x.items[i].issues.length?`<ul>${x.items[i].issues.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`:''}<details><summary>Evidências do item</summary>${x.items[i].evidenceIds.map(id=>{const s=x.evidence.find(e=>e.id===id);return `<p>${esc(s.name)} · ${s.page?'página '+s.page:esc(s.locator)}</p><blockquote>${esc(s.quote)}</blockquote>`;}).join('')}</details>${button('edit','Conferir item '+(i+1),`data-index="${i}"`)}</div>`).join('')}</div>${x.facts.length?`<details><summary>Cláusulas e autorizações identificadas</summary>${x.facts.map(f=>{const s=x.evidence.find(e=>e.id===f.evidenceId);return `<p>${esc(f.text)}</p><p>${esc(s.name)} · ${s.page?'página '+s.page:esc(s.locator)}</p><blockquote>${esc(s.quote)}</blockquote>`;}).join('')}</details>`:''}<form id="glosasForm" data-step="confirm"><div class="glosas-fields">${field('operator','Operadora',draft.operator,'required maxlength="200"')}${field('lot','Referência do lote',draft.lot,'required maxlength="200"')}</div><label class="glosas-consent"><input name="confirmed" type="checkbox" required>Conferi todas as linhas, associações, valores, evidências e divergências com os documentos originais.</label><button class="primary-action" type="submit">Confirmar e gerar análise</button></form>`;}
function analysisView(){const result=current?.automation?.analysis;if(!result)return '';return `<section><h3>Sugestões e minutas para revisão profissional</h3><p>${esc(result.notice)}</p>${result.items.map(v=>`<details><summary>Item ${v.index+1} · análise e minuta</summary><p>${esc(v.observation)}</p><ul>${v.missing.map(m=>`<li>${esc(m)}</li>`).join('')}</ul><h4>Minuta não protocolada</h4><p class="glosas-draft">${esc(v.draft||'Evidência insuficiente para preparar minuta.')}</p><h4>Prevenção</h4><p>${esc(v.prevention)}</p><p>Evidências: ${v.evidenceIds.map(id=>{const s=current.automation.extraction.evidence.find(e=>e.id===id);return esc(s?s.name+' · '+(s.page?'página '+s.page:s.locator):id);}).join('; ')}</p></details>`).join('')}</section>`;}
function lotForm(){return `${question('Qual lote vamos conferir?')}<form id="glosasForm" data-step="lot"><div class="glosas-fields">${field('operator','Operadora',draft.operator,'required maxlength="200"')}${field('lot','Referência do lote',draft.lot,'required maxlength="200"')}</div><label class="glosas-consent"><input name="consent" type="checkbox" required ${draft.consent?'checked':''}>Tenho autorização e finalidade legítima para registrar estas informações.</label><div class="glosas-toolbar"><button class="primary-action" type="submit">Continuar para os itens</button></div></form>`;}
function itemForm(){const v=draft.items[itemIndex];return `${question(`Quais são os dados do item ${itemIndex+1}?`)}<p>Use a referência da guia, sem nome, CPF ou prontuário do paciente.</p><form id="glosasForm" data-step="item"><div class="glosas-fields">${field('guide','Guia',v.guide,'required maxlength="200"')}${field('sequence','Sequência do item',v.sequence,'required maxlength="200"')}${field('code','Código informado',v.code,'maxlength="30"')}<label>Categoria informada<select name="category">${Object.entries(categories).map(([key,label])=>`<option value="${key}" ${v.category===key?'selected':''}>${label}</option>`).join('')}</select></label>${['billed','paid','denied'].map(k=>field(k,labels[k]+' (R$)',v[k]===null?'':(v[k]/100).toFixed(2),'type="number" min="0" max="10000000" step="0.01" required')).join('')}${field('reason','Motivo informado pela operadora',v.reason,'required maxlength="200"')}</div><label>Referência de evidência<textarea name="evidence" maxlength="2000" rows="2">${esc(v.evidence)}</textarea></label><div class="glosas-toolbar"><button class="primary-action" type="submit">Conferir este item</button>${current?.automation?'':button('remove','Remover este item')}</div></form>`;}
function review(){return `${question(current&&!dirty?'A conferência foi salva. O que deseja fazer agora?':'Confira os itens antes de salvar')}<div class="glosas-review">${draft.items.map((v,i)=>`<div><p><strong>Item ${i+1}</strong> · Guia ${esc(v.guide)} · sequência ${esc(v.sequence)}</p><p>Faturado ${money(v.billed)} · pago ${money(v.paid)} · glosado ${money(v.denied)}</p>${button('edit','Revisar item '+(i+1),`data-index="${i}"`)}</div>`).join('')||'<p>Nenhum item informado.</p>'}</div><div class="glosas-toolbar">${button('add','Adicionar outro item',draft.items.length>=100?'disabled':'')}${button('lot','Revisar lote')}${button('save','Salvar e conferir',!draft.items.length?'disabled':'')}</div>${current&&!dirty?`<section aria-label="Conferência salva"><h3>Resultado salvo</h3><dl class="glosas-totals">${Object.entries(current.summary.totals).map(([k,v])=>`<div><dt>${labels[k]}</dt><dd>${money(v)}</dd></div>`).join('')}</dl><p>Índice de glosa: ${current.summary.denialPercent===null?'não calculável':current.summary.denialPercent+'%'}</p><ul>${current.summary.items.flatMap((v,i)=>v.pending.map(p=>`<li>Item ${i+1}: ${esc(p)}</li>`)).join('')}</ul>${button('report','Baixar relatório preliminar')}</section>`:''}`;}
function render(scroll=false){
 if(!root)return;
 const conversation=step==='intro'?intro():reply('Sim, vamos conferir minhas glosas.')+(step==='documents'?assistant(documentForm()):step==='extraction'?assistant(extractionReview()):step==='lot'?assistant(lotForm()):reply(`Lote ${draft.lot} · ${draft.operator}`)+assistant(step==='item'?itemForm():review()+analysisView()));
 root.innerHTML=`<article class="charge-analysis-shell glosas-module"><header class="charge-analysis-header"><div class="charge-analysis-identity"><span class="charge-analysis-mark" aria-hidden="true"><img src="/assets/audita-logo-original.png" alt="" /></span><p><strong>IA AUDITA</strong> está analisando com você</p></div></header><div class="glosas-stage charge-analysis-stage"><div class="charge-analysis-conversation" aria-label="Conversa guiada sobre glosas">${conversation}</div></div><p class="glosas-status" role="alert" ${error?'':'hidden'}>${esc(error)}</p></article>`;
 root.setAttribute('aria-busy',String(busy));
 if(current?.automation){
if(step==='review'){root.querySelector('[data-glosas="add"]')?.remove();root.querySelector('[data-glosas="lot"]')?.remove();root.querySelector('[data-glosas="save"]')?.remove();const actions=document.createElement('div');actions.className='glosas-toolbar';actions.innerHTML=button('documents','Revisar documentos')+button('analyze','Gerar análise e minutas',!aiReady||!current.automation.confirmedAt?'disabled':'')+(current.automation.confirmedAt?button('pdf','Baixar relatório PDF'):'');root.querySelector('.charge-analysis-message.assistant .charge-analysis-bubble')?.append(actions);}
  if(current.automation.error){const p=document.createElement('p');p.className='glosas-status';p.setAttribute('role','alert');p.textContent=current.automation.error;root.append(p);}
  if(current.automation.busy&&Date.parse(current.automation.busy.until)>Date.now()){const p=document.createElement('p');p.setAttribute('role','status');p.textContent='Leitura em andamento. Aguarde e atualize o andamento.';root.append(p);root.querySelectorAll('button,input,textarea,select').forEach(n=>n.disabled=true);root.querySelector('[data-glosas="refresh"]').disabled=false;}
 }
 root.querySelectorAll('.glosas-toolbar:empty').forEach(n=>n.remove());
 if(busy)root.querySelectorAll('button,input,textarea,select').forEach(n=>n.disabled=true);
 motion.moveAssistantAvatar(root.querySelector('.charge-analysis-conversation'),{immediate:true});
 if(scroll){root.querySelector('.glosas-question')?.focus({preventScroll:true});motion.scrollLatestAssistant();}
}
function readDraft(){const form=root.querySelector('#glosasForm');if(!form||busy)return;const data=new FormData(form);
 if(['lot','confirm'].includes(form.dataset.step)){draft.operator=data.get('operator')||'';draft.lot=data.get('lot')||'';if(form.dataset.step==='lot')draft.consent=data.has('consent');}
 else if(form.dataset.step==='item'){const v=draft.items[itemIndex];for(const [k,value] of data)v[k]=['billed','paid','denied'].includes(k)?value===''?null:Math.round(Number(value)*100):value;}
}
async function run(fn){if(busy)return;busy=true;error='';const turn=epoch;root.setAttribute('aria-busy','true');root.querySelectorAll('button').forEach(n=>n.disabled=true);try{await fn();}catch(e){if(turn===epoch)error=e.message;}finally{if(turn===epoch){busy=false;render(true);}}}
function useCase(v){current=v;draft=structuredClone(v.data);dirty=false;step='review';if(v.automation){if(!v.automation.extraction)step='documents';else if(!v.automation.confirmedAt){step='extraction';const x=v.automation.extraction;draft={operator:x.operator,lot:x.lot,consent:true,items:x.items.map(({evidenceIds,issues,...item})=>({...item,guide:item.guide||'',sequence:item.sequence||'',code:item.code||'',reason:item.reason||''}))};}}}
function addItem(){draft.items.push({guide:'',sequence:String(draft.items.length+1),code:'',category:'unknown',reason:'',billed:0,paid:0,denied:0,evidence:''});itemIndex=draft.items.length-1;step='item';dirty=true;}
async function activate(){if(document.body.dataset.activePage!=='auditoria-glosas')return;await run(async()=>{const turn=epoch;const auth=await fetch('/api/auth/me',{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error('Sessão indisponível.');return r.json();});const config=await api('/config');if(turn!==epoch)return;user=auth.user;ready=config.storageReady;aiReady=config.aiReady;if(user&&ready)cases=(await api('/cases')).cases;});}
root?.addEventListener('input',e=>{if(!e.target.closest('#glosasForm'))return;readDraft();dirty=true;});
async function command(action){useCase((await api('/cases/'+current.id+'/actions','POST',{action,revision:current.revision,requestId:crypto.randomUUID()})).case);}
root?.addEventListener('submit',e=>{e.preventDefault();if(!user){document.querySelector('#loginButton')?.click();return;}
 const form=e.target,data=new FormData(form);
 if(['create','upload','confirm'].includes(form.dataset.step)){
  readDraft();void run(async()=>{
   if(form.dataset.step==='create'){useCase((await api('/cases','POST',{data:{operator:'A identificar no documento',lot:'Novo lote documental',consent:true,items:[]},aiConsent:data.has('aiConsent')})).case);cases=(await api('/cases')).cases;}
   if(form.dataset.step==='upload'){
    const file=data.get('file');if(!file?.size||file.size>10*1024*1024)throw Error('Envie um documento de até 10 MB.');
    const turn=epoch,res=await fetch('/api/glosas/cases/'+current.id+'/documents?'+new URLSearchParams({name:file.name,type:data.get('type'),revision:current.revision}),{method:'POST',credentials:'same-origin',body:file});const value=await res.json();if(turn!==epoch)return;if(!res.ok)throw Error(value.message||'Não foi possível enviar.');useCase(value.case);
   }
   if(form.dataset.step==='confirm'){
    const incomplete=draft.items.findIndex(v=>!v.guide.trim()||!v.sequence.trim()||!v.reason.trim()||[v.billed,v.paid,v.denied].some(n=>n===null)||v.paid+v.denied>v.billed);
    if(incomplete>=0){itemIndex=incomplete;step='item';throw Error('Confira os campos ausentes ou inconsistentes deste item.');}
    useCase((await api('/cases/'+current.id,'PUT',{data:draft,revision:current.revision,confirmed:data.has('confirmed')})).case);await command('analyze');cases=(await api('/cases')).cases;
   }
  });return;
 }
 readDraft();error='';dirty=true;
 if(step==='lot'){if(!draft.items.length)addItem();else step='review';}
 else {const v=draft.items[itemIndex];if(v.paid+v.denied>v.billed)error='Pago e glosado excedem o faturado. Confira os valores.';else if(draft.items.some((other,i)=>i!==itemIndex&&other.guide.trim()===v.guide.trim()&&other.sequence.trim()===v.sequence.trim()))error='Esta guia e sequência já estão no lote.';else step=current?.automation?'extraction':'review';}
 render(true);
});
root?.addEventListener('click',e=>{const target=e.target.closest('[data-glosas]');if(!target||busy)return;
 if(!user){document.querySelector('#loginButton')?.click();return;}
 readDraft();error='';const action=target.dataset.glosas;
 if(action==='start'){if(!ready)error='Armazenamento seguro indisponível. Tente novamente mais tarde.';else step='documents';render(true);return;}
 if(action==='documents'){if(dirty&&!confirm('Descartar alterações não salvas?'))return;step='documents';render(true);return;}
 if(action==='add'){if(draft.items.length<100)addItem();render(true);return;}
 if(action==='edit'){itemIndex=Number(target.dataset.index);step='item';render(true);return;}
 if(action==='lot'){step='lot';render(true);return;}
 if(action==='remove'){draft.items.splice(itemIndex,1);dirty=true;step='review';render(true);return;}
 if(action==='new'){if(dirty&&!confirm('Descartar alterações não salvas?'))return;current=null;draft=fresh();dirty=false;step='intro';render(true);return;}
 const selected=root.querySelector('#glosasSaved')?.value;
 if(action==='open'&&(!selected||(dirty&&!confirm('Descartar alterações não salvas?'))))return;
 if(action==='delete'&&!confirm('Excluir definitivamente este lote?'))return;
 void run(async()=>{
  if(action==='extract'){if(current.automation.extraction&&!confirm('Uma nova leitura substituirá a conferência e as minutas. Continuar?'))return;await command('extract');}
  if(action==='analyze')await command('analyze');
  if(action==='refresh'){if(dirty&&!confirm('Descartar alterações não salvas e atualizar?'))return;useCase((await api('/cases/'+current.id)).case);}
  if(action==='save'){useCase((await api('/cases'+(current?'/'+current.id:''),current?'PUT':'POST',{data:draft,revision:current?.revision})).case);cases=(await api('/cases')).cases;}
  if(action==='open')useCase((await api('/cases/'+selected)).case);
  if(action==='delete'){await api('/cases/'+current.id,'DELETE',{revision:current.revision});current=null;draft=fresh();dirty=false;step='intro';cases=(await api('/cases')).cases;}
  if(action==='report'||action==='pdf'){const turn=epoch;const res=await fetch('/api/glosas/cases/'+current.id+(action==='pdf'?'/report.pdf':'/report'),{credentials:'same-origin'});if(!res.ok)throw Error('Não foi possível baixar o relatório.');const blob=await res.blob();if(turn!==epoch)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='glosas-preliminar.'+(action==='pdf'?'pdf':'txt');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 });
});
document.addEventListener('audita:pagechange',()=>{readDraft();void activate();});
window.addEventListener('audita:auth-changed',()=>{epoch++;user=null;current=null;draft=fresh();cases=[];busy=false;dirty=false;error='';step='intro';render();void activate();});
window.addEventListener('resize',()=>{if(root?.querySelector('.glosas-stage'))motion.moveAssistantAvatar(root.querySelector('.charge-analysis-conversation'),{immediate:true});});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(root){render();void activate();}
