import {createAuditaChatMotion} from './audita-chat-motion.js';
const root=document.querySelector('#importApp');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
let config={},user=null,current=null,cases=[],queue=[],busy=false,error='',epoch=0,timer;
let editingDocuments=false,draftProducts=null,productIndex=0;
let draftCheck=null,documentSummary=false;
const docFields={description:'Descrição em português',original:'Descrição original',productCode:'Código do produto',manufacturer:'Fabricante',manufacturerCode:'Código do fabricante',model:'Modelo',materials:'Materiais',application:'Aplicação',specifications:'Características técnicas',quantity:'Quantidade',unit:'Unidade',unitValue:'Valor unitário',totalValue:'Valor total do item',currency:'Moeda',netWeight:'Peso líquido do item',grossWeight:'Peso bruto do item',weightUnit:'Unidade de peso'};
const docSides={invoice:'Invoice',packing:'Packing List',technical:'Ficha técnica'};
const commercialFields=['quantity','unit','unitValue','totalValue','currency','netWeight','grossWeight','weightUnit'];
const docLine=id=>draftCheck.lines.find(l=>l.id===id);
const origin=l=>`${current.documents.find(d=>d.id===l.documentId)?.name||'Documento'} · página ${l.page??'não identificada'} · linha ${l.line||'não identificada'}`;
const memberIds=g=>Object.keys(docSides).map(s=>g[s+'Id']).filter(Boolean);
const newGroup=l=>({invoiceId:null,packingId:null,technicalId:null,[current.documents.find(d=>d.id===l.documentId).type+'Id']:l.id,selected:{},note:'',acknowledged:false});
const motion=createAuditaChatMotion({getStage:()=>root.querySelector('.import-stage'),getConversation:()=>root.querySelector('.charge-analysis-conversation'),isActive:()=>document.body.dataset.activePage==='auditoria-importacao'});
const assistant=html=>`<div class="charge-analysis-message assistant"><span class="charge-analysis-avatar-anchor" aria-hidden="true"></span><div class="charge-analysis-bubble">${html}</div></div>`;
const reply=html=>`<div class="charge-analysis-message user"><div class="charge-analysis-bubble"><span class="charge-analysis-visually-hidden">Solicitante: </span>${html}</div></div>`;
const question=text=>`<h3 class="import-question" tabindex="-1">${text}</h3>`;
const statuses={documents:'Documentos',products:'Conferência dos produtos',review:'Revisão fiscal pendente',reviewed:'Premissas revisadas'};
async function api(path,options={}){const turn=epoch;const res=await fetch('/api/import-audit'+path,{...options,credentials:'same-origin',headers:typeof options.body==='string'?{'content-type':'application/json'}:options.headers});const data=await res.json();if(turn!==epoch)throw Error('Sessão alterada.');if(!res.ok)throw Error(data.message||'Não foi possível continuar.');return data;}
const button=(action,label,extra='')=>`<button type="button" class="secondary-action" data-import="${action}" ${extra}>${label}</button>`;
const input=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" rows="3" maxlength="4000" required>${esc(value)}</textarea></label>`;
const check=(name,label)=>`<label class="audit-consent"><input type="checkbox" name="${name}" required>${label}</label>`;
const submit=label=>`<button class="primary-action" type="submit">${label}</button>`;
function productFields(p,index){return `<fieldset class="import-product" data-product="${index}"><legend>Produto ${index+1}</legend>${area('description','Descrição em português',p.description)}${area('original','Descrição original',p.original)}${area('specifications','Características técnicas conhecidas',p.specifications)}${input('quantity','Quantidade informada',p.quantity)}${input('value','Valor no documento (não é valor aduaneiro)',p.value)}${input('currency','Moeda',p.currency)}<label>Documento de origem<select name="documentId" required>${current.documents.map(d=>`<option value="${d.id}" ${d.id===p.documentId?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label>${input('page','Página (deixe vazio para XML ou se desconhecida)',p.page,'number','min="1" max="5000"')}${button('remove-product','Remover item duplicado ou não pertinente',`data-index="${index}"`)}</fieldset>`;}
function reviewForm(){const saved=current.review;return `<details ${saved?'':'open'}><summary>Revisão fiscal · equipe autorizada</summary><p>Confira classificação, descrição integral dos atos, condições e vigência. Nenhuma alíquota é preenchida pela IA. Revise os valores em reais, incluindo frete/seguro no valor aduaneiro quando aplicável. Esta versão não calcula regimes especiais, tributos específicos ou outros impostos.</p><form class="import-form" data-import-form="review">${input('operationDate','Data da operação',saved?.operationDate,'date','required')}${area('note','Conclusão e pendências da revisão',saved?.note)}${current.products.map((p,index)=>{const r=saved?.rows.find(r=>r.index===index)||{};const candidates=current.suggestions.items.find(s=>s.index===index)?.candidates||[];return `<fieldset class="import-product" data-review="${index}"><legend>${index+1}. ${esc(p.description)}</legend><label>NCM conferida<select name="ncm" required><option value="">Selecione após conferir</option>${candidates.map(c=>`<option value="${c.code}" ${r.ncm===c.code?'selected':''}>${c.code} · ${esc(c.official.description)}</option>`).join('')}</select></label>${[['customsValueCents','Valor aduaneiro total do item (R$)'],['otherIpiBaseCents','Demais parcelas legais da base de IPI (R$)'],['iiBps','II de referência (%)'],['ipiBps','IPI de referência (%)'],['scenarioIiBps','II do cenário (%)'],['scenarioIpiBps','IPI do cenário (%)']].map(([k,l])=>input(k,l,r[k]==null?'':r[k]/100,'number',`min="0" step="0.01" max="${k.endsWith('Bps')?300:1000000000}" required`)).join('')}${input('iiSource','Fonte oficial da alíquota/benefício de II',r.iiSource,'url','required')}${input('ipiSource','Fonte oficial da alíquota/Ex de IPI',r.ipiSource,'url','required')}${area('basis','Atos, vigência, requisitos técnicos e fundamento dos dois cenários',r.basis)}</fieldset>`;}).join('')}${check('standardAdValorem','Confirmei que o cálculo é ad valorem e que estas bases representam a operação, sem regime especial não coberto.')}${check('confirmed','Conferi todos os produtos, alíquotas, atos, vigências e condições; esta revisão não representa aprovação da Receita.')}${submit('Registrar revisão e calcular II/IPI')}</form></details>`;}
function result(){return `<section aria-label="Sugestões fiscais"><h3>NCMs candidatas · revisão obrigatória</h3><p>${esc(current.suggestions.notice)} Consulta: ${esc(current.suggestions.fetchedAt)}.</p>${current.suggestions.items.map(s=>`<div class="import-result"><h4>${s.index+1}. ${esc(current.products[s.index].description)}</h4>${s.candidates.length?s.candidates.map(c=>`<p><strong>${esc(c.code)}</strong> · ${esc(c.official.description)}<br>Fundamento sugerido: ${esc(c.reason)}<br>Ato na tabela NCM: ${esc(c.official.act)}</p>`).join(''):'<p>Nenhuma candidata validada na tabela vigente. Complete as características e pesquise novamente.</p>'}${s.missing.length?`<p>Pontos para conferir: ${s.missing.map(esc).join('; ')}</p>`:''}</div>`).join('')}<h3>Fontes e possíveis benefícios</h3>${current.research?`<p>${esc(current.research.notice)}</p><p class="import-research">${esc(current.research.text)}</p><ul>${current.research.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a></li>`).join('')}</ul>`:`<p role="status">${esc(current.researchError||'Benefícios não pesquisados.')}</p>`}</section>`;}
function uploadForm(){return `<form class="import-form" data-import-form="upload"><label>Tipo de documento<select name="type"><option value="invoice">Invoice</option><option value="packing">Packing List</option><option value="technical">Ficha técnica</option></select></label><label>Arquivo PDF, PNG, JPEG ou XML<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.xml" required></label><p class="import-notice">Até quatro arquivos, 10 MB por arquivo e 20 MB no total.</p>${submit('Enviar documento')}</form>`;}
function productQuestion(){
 if(!draftProducts)draftProducts=current.products.map(p=>({...p}));
 const last=productIndex===draftProducts.length-1;
 return question(`Vamos conferir o produto ${productIndex+1} de ${draftProducts.length}?`)+`<p>Confira a tradução e as características. Invoice e Packing List podem repetir itens; remova duplicidades. Os valores transcritos não entram automaticamente no cálculo.</p>${(current.warnings||[]).map(w=>`<p role="status">${esc(w)}</p>`).join('')}<form class="import-form" data-import-form="products">${productFields(draftProducts[productIndex],productIndex)}${last?check('confirmed','Conferi todos os produtos, suas características e referências documentais.'):''}<div class="import-actions">${productIndex?button('previous-product','Produto anterior'):''}${submit(last?'Salvar e confirmar produtos':'Próximo produto')}</div></form>`;
}
function documentQuestion(){
 if(!draftCheck)draftCheck=structuredClone(current.documentCheck);
 productIndex=Math.min(productIndex,draftCheck.groups.length-1);
 if(documentSummary)return question('Resumo da conferência documental')+`<p>Esta conferência não é aprovação fiscal. Informações não verificáveis continuam pendentes, mesmo quando reconhecidas.</p><ol>${draftCheck.groups.map((g,i)=>{const c=draftCheck.comparisons[i];return `<li>${esc(docLine(memberIds(g)[0]).description||'Descrição ausente')} · ${g.acknowledged?'Conferência reconhecida':'A conferir'} · ${c.rows.filter(r=>r.status==='coincidente').length} verificações coincidentes, ${c.divergent} divergentes, ${c.rows.filter(r=>r.status==='não verificável').length} não verificáveis. ${button('check-item','Rever produto',`data-index="${i}"`)}</li>`;}).join('')}</ol>${draftCheck.excluded.length?`<details><summary>Itens não pertinentes (${draftCheck.excluded.length})</summary>${draftCheck.excluded.map(e=>`<p>${esc(docLine(e.id).description)} · ${esc(e.reason)} ${button('restore-line','Reincluir',`data-id="${e.id}"`)}</p>`).join('')}</details>`:''}<p>${current.extraction.totals.length} total(is) de documento preservado(s), sem atribuição aos itens.</p><form data-import-form="confirm-check" class="import-form">${check('confirmed','Reconheço as divergências e informações não verificáveis listadas; posso prosseguir para a pesquisa fiscal, sujeita à revisão da equipe.')}${submit('Confirmar conferência e continuar')}</form><a href="/api/import-audit/cases/${current.id}/report">Baixar conferência documental em PDF</a>`;
 const g=draftCheck.groups[productIndex],comparison=draftCheck.comparisons[productIndex]||{rows:[]};
 function sourcePanel(side){
  const l=docLine(g[side+'Id']);
  const available=draftCheck.groups.filter(v=>v!==g&&memberIds(v).length===1&&v[side+'Id']).map(v=>docLine(v[side+'Id']));
  if(!l)return `<section class="import-source"><h4>${docSides[side]}</h4><p>Sem item associado. Não será considerado conferido.</p>${available.length?`<label>Associar manualmente<select name="link-${side}"><option value="">Escolha a linha correspondente</option>${available.map(v=>`<option value="${v.id}">${esc(v.productCode||'Sem código')} · ${esc(v.description||v.original||'Sem descrição')} · ${esc(origin(v))}</option>`).join('')}</select></label>${button('link-line','Confirmar associação',`data-side="${side}"`)}`:''}</section>`;
  const original=current.extraction.lines.find(v=>v.id===l.id);
  return `<section class="import-source"><h4>${docSides[side]}</h4><p class="import-notice">${esc(origin(l))}</p><dl>${Object.entries(docFields).map(([k,label])=>`<div><dt>${label}</dt><dd>${esc(l[k]??'Não informado')}</dd></div>`).join('')}</dl><details><summary>Corrigir transcrição · ${docSides[side]}</summary><p>Deixe vazio o que não consta no documento. A extração original será preservada.</p>${Object.entries(docFields).map(([k,label])=>`<label>${label}<textarea name="${l.id}.${k}" rows="2" maxlength="${k==='specifications'?4000:commercialFields.includes(k)?100:2000}">${esc(l[k])}</textarea></label>`).join('')}${input(l.id+'.page','Página',l.page,'number','min="1" max="5000"')}${input(l.id+'.line','Linha de origem',l.line,'text','maxlength="2000"')}<label>Separador decimal confirmado<select name="${l.id}.numberFormat">${[['auto','Não confirmado'],['dot','Ponto (ex.: 1234.50)'],['comma','Vírgula (ex.: 1234,50)']].map(([v,label])=>`<option value="${v}" ${l.numberFormat===v?'selected':''}>${label}</option>`).join('')}</select></label><p>Não use separadores de milhares. Números ambíguos permanecem não verificáveis até a confirmação/correção.</p></details><details><summary>Extração original · ${docSides[side]}</summary><p>${esc(origin(original))}</p><dl>${Object.entries(docFields).map(([k,label])=>`<div><dt>${label}</dt><dd>${esc(original[k]??'Não informado')}</dd></div>`).join('')}</dl></details>${memberIds(g).length>1?button('unlink-line','Desfazer vínculo',`data-id="${l.id}"`):''}</section>`;
 }
 const pair=draftCheck.suggestedPairs.find(p=>p.invoiceId===g.invoiceId&&!g.packingId&&draftCheck.groups.some(v=>v.packingId===p.packingId&&memberIds(v).length===1));
 const choices=Object.entries(docFields).map(([k,label])=>{
  const values=Object.keys(docSides).filter(s=>g[s+'Id']&&docLine(g[s+'Id'])[k]&&!(s==='technical'&&commercialFields.includes(k)));
  if(values.length<2||new Set(values.map(s=>docLine(g[s+'Id'])[k])).size<2)return '';
  return `<label>${label} · dado a utilizar<select name="select-${k}"><option value="">Escolha a origem se houver conflito</option>${values.map(s=>`<option value="${s}" ${g.selected[k]===s?'selected':''}>${docSides[s]}: ${esc(docLine(g[s+'Id'])[k])}</option>`).join('')}</select></label>`;
 }).join('');
 return question(`Conferência documental · produto ${productIndex+1} de ${draftCheck.groups.length}`)+`<p>Associe somente linhas do mesmo produto. Não somamos embalagens ou remessas parciais. A ausência de preço no Packing List não é um erro; ficha técnica não substitui evidência comercial.</p>${(current.warnings||[]).map(w=>`<p role="status">${esc(w)}</p>`).join('')}<form data-import-form="document-check" class="import-form">${pair?`<p>Código único correspondente encontrado. Confira os documentos antes de aceitar.</p>${button('suggest-pair','Aceitar associação sugerida',`data-id="${pair.packingId}"`)}`:''}<div class="import-document-columns">${sourcePanel('invoice')}${sourcePanel('packing')}</div><details ${g.technicalId?'open':''}><summary>Ficha técnica complementar</summary>${sourcePanel('technical')}</details><section aria-label="Resultado da comparação"><h4>Comparação Invoice × Packing List</h4><p>Valores referentes à última gravação. Salve correções para recalcular.</p>${comparison.rows.map(r=>`<div class="import-comparison"><strong>${esc(r.label)} · ${r.status}</strong><p>Invoice: ${esc(r.left??'ausente')} · Packing List: ${esc(r.right??'ausente')}</p><p class="import-notice">${esc(r.reason)}</p></div>`).join('')}</section>${choices}<label>Justificativa das correções ou valores conflitantes<textarea name="note" maxlength="2000" rows="3">${esc(g.note)}</textarea></label><label class="audit-consent"><input type="checkbox" name="acknowledged" ${g.acknowledged?'checked':''}>Conferi esta associação e reconheço as informações divergentes ou não verificáveis acima.</label><div class="import-actions">${button('check-previous','Produto anterior',productIndex?'':'disabled')}${submit('Salvar e comparar')}${button('check-next','Salvar e próximo produto')}${button('check-summary','Salvar e ver resumo')}</div><details><summary>Indicar item não pertinente</summary><p>A linha permanece no histórico. Justifique por que não pertence a esta conferência.</p><label>Linha<select name="exclude-id">${memberIds(g).map(id=>`<option value="${id}">${esc(origin(docLine(id)))}</option>`).join('')}</select></label><label>Justificativa da exclusão<textarea name="exclude-reason" maxlength="2000" rows="2"></textarea></label>${button('exclude-line','Marcar como não pertinente')}</details></form><details><summary>Totais dos documentos (não atribuídos aos produtos)</summary>${current.extraction.totals.map(t=>`<p>${esc(origin(t))} · ${esc(t.label)}: ${esc(t.value??'ausente')} ${esc(t.unit)}</p>`).join('')||'<p>Não identificados.</p>'}</details>`;
}
function readCheck(){
 const f=root.querySelector('[data-import-form=document-check]');if(!f)return;
 const g=draftCheck.groups[productIndex],data=new FormData(f);
 for(const id of memberIds(g)){const l=docLine(id);for(const k of [...Object.keys(docFields),'page','line','numberFormat']){const v=data.get(id+'.'+k);l[k]=k==='page'?(v?Number(v):null):v||null;}}
 g.selected={};for(const k of Object.keys(docFields)){const v=data.get('select-'+k);if(v)g.selected[k]=v;}
 g.note=data.get('note');g.acknowledged=data.has('acknowledged');
}
async function saveCheck(){const index=productIndex;await command('products',{documentCheck:draftCheck,confirmed:false});draftCheck=structuredClone(current.documentCheck);productIndex=Math.min(index,draftCheck.groups.length-1);}
function linkLine(id){
 const g=draftCheck.groups[productIndex],target=draftCheck.groups.find(v=>memberIds(v).length===1&&memberIds(v)[0]===id);
 if(!target)throw Error('Desfaça o vínculo anterior antes de associar esta linha.');
 const side=current.documents.find(d=>d.id===docLine(id).documentId).type;
 if(g[side+'Id'])throw Error('Já existe um documento desse tipo no produto.');
 g[side+'Id']=id;g.acknowledged=false;g.selected={};draftCheck.groups=draftCheck.groups.filter(v=>v!==target);productIndex=draftCheck.groups.indexOf(g);
}
function simulation(){return question('Simulação de II/IPI · premissas revisadas')+`<p>A equipe registrou a revisão. Confira os resultados e baixe seu relatório.</p><p class="import-notice">Revisor ${esc(current.review.by)} · ${esc(current.review.at)}. Data da operação: ${esc(current.review.operationDate)}.</p>${current.review.rows.map(r=>`<div class="import-result"><strong>Produto ${r.index+1} · NCM ${r.ncm}</strong><p>Referência: II ${money(r.calculation.reference.iiCents)} + IPI ${money(r.calculation.reference.ipiCents)}.<br>Cenário: II ${money(r.calculation.proposed.iiCents)} + IPI ${money(r.calculation.proposed.ipiCents)}.<br>Diferença simulada: ${money(r.calculation.differenceCents)} (não é economia garantida).</p></div>`).join('')}`;}
function conversation(){
 if(!current)return assistant(`<h2>Entenda a classificação e os tributos da sua importação</h2><p>Envie a Invoice e o Packing List para comparar quantidades, pesos e valores, produto por produto. A ficha técnica pode complementar as características.</p><p>Primeiro, você confere as associações e eventuais divergências. Depois, pesquisamos NCMs e possíveis benefícios em fontes oficiais. A equipe revisa tudo antes de simular II e IPI.</p><p>Sem promessa de economia ou desembaraço. A NCM depende das características do produto.</p>${question('Podemos começar?')}<form class="import-form" data-import-form="create">${check('consent','Tenho autorização para enviar estes documentos e autorizo a leitura pela OpenAI e pela equipe Audita.')}${submit('Sim, vamos começar')}</form>${!config.storageReady||!config.aiReady?`<p class="import-notice" role="status">Atendimento indisponível neste ambiente: ${[!config.storageReady?'armazenamento seguro':'',!config.aiReady?'integração OpenAI':''].filter(Boolean).join(' e ')} pendente(s).</p>`:''}`);
 const docs=current.documents;
 let history=reply('<p>Autorizei a leitura dos documentos para esta auditoria.</p>');
 if(!docs.length)return history+assistant(question('Documentos da importação')+'<p>Vamos começar pela Invoice (fatura comercial). Se preferir, envie o Packing List ou a ficha técnica. Esses documentos ajudam a identificar os produtos e suas características.</p>'+(current.permissions.owner?uploadForm():'<p>Aguardando o envio pelo solicitante.</p>'));
 history+=assistant('<p>Para entender seus produtos, preciso dos documentos da importação.</p>')+reply(`<p>Documentos enviados:</p><ul>${docs.map(d=>`<li><a href="/api/import-audit/cases/${current.id}/documents/${d.id}">${esc(d.name)}</a></li>`).join('')}</ul>`);
 if(current.busy||processing)return history+assistant(question(processing==='suggest'||current.busy?.action==='suggest'?'Pesquisando NCMs e fontes oficiais…':'Lendo seus documentos…')+'<p role="status">Aguarde enquanto organizo as informações. Você pode sair e retomar este atendimento. Se o processamento for interrompido, uma nova tentativa fica disponível em até 15 minutos.</p>');
 if(editingDocuments)return history+assistant(question('Quer complementar os documentos?')+'<p>Enviar um novo arquivo invalida a conferência e a revisão anteriores. Não envie dados sem relação com a importação.</p>'+uploadForm()+button('cancel-documents','Voltar à conversa'));
 if(!current.products.length)return history+assistant(question('Recebi os documentos. Posso fazer a leitura?')+`<p>Vou organizar as descrições, quantidades e características para você conferir.</p><div class="charge-analysis-actions">${button('extract','Ler documentos com IA')}${button('edit-documents','Enviar outro documento')}</div>`);
 if(current.extraction&&(!current.confirmed||draftCheck)&&current.permissions.owner)return history+assistant(documentQuestion());
 if((!current.confirmed||draftProducts)&&current.permissions.owner)return history+assistant(productQuestion());
 history+=assistant('<p>Organizei os produtos para conferência.</p>');
 if(current.confirmed)history+=reply(`<p>Conferi ${current.products.length} produto(s) e suas referências documentais.</p>`);
 const corrections=current.permissions.owner?`<div class="import-actions">${button('edit-products','Corrigir produtos')}${button('edit-documents','Complementar documentos')}</div>`:'';
 if(!current.suggestions)return history+assistant(question('Vamos pesquisar o enquadramento dos produtos?')+`<p>${current.extraction?'Conferência documental registrada; pendências reconhecidas não são informações verificadas.':'Atendimento sem comparação documental.'}</p><p>Vou buscar NCMs candidatas e referências oficiais sobre possíveis benefícios. A pesquisa precisa ser revisada pela equipe antes de calcular os impostos.</p>${current.permissions.owner?button('suggest','Pesquisar NCMs e possíveis benefícios'):'<p>Aguardando a conferência e a pesquisa pelo solicitante.</p>'}<a href="/api/import-audit/cases/${current.id}/report">Baixar conferência documental em PDF</a>${corrections}`);
 history+=assistant(`<p>A pesquisa está disponível. As NCMs são candidatas, não uma classificação definitiva.</p><details class="import-findings"><summary>Ver NCMs e fontes pesquisadas</summary>${result()}</details>`);
 const next=current.review?simulation():question('Agora, a equipe precisa revisar')+'<p>O próximo passo é conferir o enquadramento, os atos e as alíquotas. A simulação só fica disponível depois dessa revisão.</p>';
 return history+assistant(next+`<a class="secondary-action" href="/api/import-audit/cases/${current.id}/report">Baixar relatório ${current.review?'revisado':'preliminar'}</a>${current.permissions.reviewer?reviewForm():''}${corrections}${current.permissions.owner?button('suggest','Refazer pesquisa'):''}`);
}
let processing='';
function render(scroll=false){
 if(!root)return;clearTimeout(timer);
 root.innerHTML=`<article class="charge-analysis-shell import-module"><header class="charge-analysis-header"><div class="charge-analysis-identity"><span class="charge-analysis-mark" aria-hidden="true"><img src="/assets/audita-logo-original.png" alt="" /></span><p><strong>IA AUDITA</strong> está analisando com você</p></div></header>${current?`<div class="import-toolbar">${button('list','Meus atendimentos')}${button('refresh','Atualizar andamento')}<span class="import-notice">${esc(statuses[current.status]||current.status)} · ${esc(current.id.slice(0,8))}</span></div>`:''}<div class="import-stage charge-analysis-stage"><div class="charge-analysis-conversation" aria-label="Conversa guiada sobre sua importação">${conversation()}</div></div><p class="import-error" role="alert" ${error||current?.error?'':'hidden'}>${esc(error||current?.error||'')}</p><details class="import-limits"><summary>Limites desta análise</summary><p class="import-notice">${esc(config.notice||'Auditoria assistida: sujeita à revisão fiscal. Não registra DI/Duimp nem garante benefícios.')}</p></details>${current?`<details><summary>Histórico do atendimento</summary><ul>${current.events.map(e=>`<li>${esc(e.at)} · ${esc(e.label)}</li>`).join('')}</ul></details>`:user?`<details><summary>Retomar meus atendimentos</summary><div class="import-actions">${cases.map(c=>button('open',`${esc(statuses[c.status]||c.status)} · ${esc(c.id.slice(0,8))}`,`data-id="${c.id}"`)).join('')||'<p>Nenhum atendimento registrado.</p>'}</div></details>${config.reviewer?`<details><summary>Aguardando revisão da equipe</summary><div class="import-actions">${queue.map(c=>button('open',esc(c.id),`data-id="${c.id}"`)).join('')||'<p>Nenhum atendimento aguardando.</p>'}</div></details>`:''}`:''}</article>`;
 if(current?.products.length&&!current.extraction){const label=document.createElement('p');label.className='import-notice';label.textContent='Atendimento sem comparação documental. O valor antigo não foi reinterpretado como preço unitário.';root.querySelector('.import-toolbar').after(label);}
 if(current?.previousDocumentChecks?.length){
  const previousChecks=document.createElement('details');previousChecks.innerHTML=`<summary>Versões anteriores da conferência (${current.previousDocumentChecks.length})</summary><p class="import-notice">Registros históricos, não vigentes. O PDF inclui as extrações e transcrições anteriores.</p>${current.previousDocumentChecks.map(v=>`<details><summary>${esc(v.at)}</summary>${v.documentCheck.groups.map((g,i)=>`<p>Associação ${i+1}: Invoice ${esc(g.invoiceId||'ausente')} / Packing List ${esc(g.packingId||'ausente')} / Ficha ${esc(g.technicalId||'ausente')}. ${esc(g.note||'Sem justificativa registrada.')}</p>`).join('')}${v.documentCheck.excluded.map(e=>`<p>Não pertinente: ${esc(e.id)} · ${esc(e.reason)}</p>`).join('')}</details>`).join('')}`;root.querySelector('.import-module').append(previousChecks);
 }
 const log=root.querySelector('.charge-analysis-conversation'),previous=[...log.children].slice(0,-1);
 if(previous.length){
  const dialog=document.createElement('dialog');dialog.className='import-previous';dialog.id='importPrevious';dialog.setAttribute('aria-labelledby','importPreviousTitle');
  dialog.innerHTML='<header><h2 id="importPreviousTitle">Conversa anterior</h2><button type="button" class="secondary-action" data-import-view="close" autofocus>Fechar</button></header><div class="import-previous-messages"></div>';
  dialog.querySelector('.import-previous-messages').append(...previous);root.querySelector('.import-module').append(dialog);
  const trigger=document.createElement('button');trigger.type='button';trigger.className='secondary-action';trigger.dataset.importView='open';trigger.textContent='Ver conversa anterior';trigger.setAttribute('aria-haspopup','dialog');
  root.querySelector('.import-toolbar').append(trigger);
 }
 root.setAttribute('aria-busy',String(busy||!!current?.busy));
 root.querySelectorAll('button,input,textarea,select').forEach(el=>{el.disabled=busy||!!current?.busy;});
 root.querySelector('[data-import=refresh]')?.removeAttribute('disabled');
 if(!config.storageReady)root.querySelector('[data-import-form=create] button')?.setAttribute('disabled','');
 if(!config.aiReady)root.querySelectorAll('[data-import=extract],[data-import=suggest]').forEach(el=>el.disabled=true);
 motion.moveAssistantAvatar(root.querySelector('.charge-analysis-conversation'),{immediate:true});
 if(scroll){const target=log.lastElementChild;target?.querySelector('.import-question')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});target?.classList.add('import-new-message');}
 if(current?.busy&&document.body.dataset.activePage==='auditoria-importacao')timer=setTimeout(()=>run(async()=>{current=(await api('/cases/'+current.id)).case;},false),5000);
}
async function run(fn,scroll=true){if(busy)return;busy=true;error='';const turn=epoch;root?.setAttribute('aria-busy','true');root?.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){if(turn===epoch)error=e.message;}finally{if(turn===epoch){busy=false;processing='';render(scroll);}}}
function setCase(c){current=c;draftProducts=null;draftCheck=null;documentSummary=false;productIndex=0;editingDocuments=false;const u=new URL(location.href);u.searchParams.set('importCase',c.id);history.replaceState(null,'',u);}
async function command(action,data={}){if(['extract','suggest'].includes(action)){processing=action;render(true);}setCase((await api('/cases/'+current.id+'/actions',{method:'POST',body:JSON.stringify({action,revision:current.revision,...data})})).case);}
function readProducts(form){return [...form.querySelectorAll('[data-product]')].map(f=>Object.fromEntries(['description','original','quantity','value','currency','specifications','documentId','page'].map(k=>{const v=f.querySelector(`[name=${k}]`).value;return [k,k==='page'?(v?Number(v):null):['quantity','value','currency'].includes(k)?v||null:v];})));}
const hundredths=v=>{if(!/^\d+(\.\d{1,2})?$/.test(v))throw Error('Use números positivos com até duas casas decimais.');const [a,b='']=v.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));};
root?.addEventListener('submit',e=>{const f=e.target,action=f.dataset.importForm;if(!action)return;e.preventDefault();const d=new FormData(f);void run(async()=>{
 if(action==='create')setCase((await api('/cases',{method:'POST',body:JSON.stringify({consent:d.has('consent')})})).case);
 else if(action==='upload'){const file=d.get('file');if(file.size>10*1024*1024)throw Error('Limite de 10 MB por arquivo.');setCase((await api(`/cases/${current.id}/documents?${new URLSearchParams({name:file.name,type:d.get('type'),revision:current.revision})}`,{method:'POST',body:file})).case);}
 else if(action==='products'){draftProducts[productIndex]=readProducts(f)[0];if(productIndex<draftProducts.length-1)productIndex++;else await command('products',{products:draftProducts,confirmed:d.has('confirmed')});}
 else if(action==='document-check'){readCheck();await saveCheck();}
 else if(action==='confirm-check')await command('products',{documentCheck:draftCheck,confirmed:d.has('confirmed')});
 else if(action==='review'){const rows=[...f.querySelectorAll('[data-review]')].map(el=>{const row={index:Number(el.dataset.review)};el.querySelectorAll('[name]').forEach(v=>{row[v.name]=v.name.endsWith('Cents')||v.name.endsWith('Bps')?hundredths(v.value):v.value;});return row;});await command('review',{review:{rows,operationDate:d.get('operationDate'),note:d.get('note'),confirmed:d.has('confirmed'),standardAdValorem:d.has('standardAdValorem')}});}
 });});
root?.addEventListener('click',e=>{const b=e.target.closest('[data-import]');if(!b)return;void run(async()=>{
 const action=b.dataset.import;
 if(action==='open')setCase((await api('/cases/'+b.dataset.id)).case);
 else if(action==='refresh')setCase((await api('/cases/'+current.id)).case);
 else if(action==='edit-documents')editingDocuments=true;
 else if(action==='cancel-documents')editingDocuments=false;
 else if(action==='edit-products'){if(current.extraction)draftCheck=structuredClone(current.documentCheck);else draftProducts=current.products.map(p=>({...p}));productIndex=0;documentSummary=false;}
 else if(['suggest-pair','link-line','unlink-line','exclude-line','check-next','check-previous','check-summary'].includes(action)){
  readCheck();const g=draftCheck.groups[productIndex],f=root.querySelector('[data-import-form=document-check]');
  if(action==='suggest-pair')linkLine(b.dataset.id);
  if(action==='link-line'){const id=f.elements['link-'+b.dataset.side].value;if(!id)throw Error('Escolha uma linha.');linkLine(id);}
  if(action==='unlink-line'){g[ current.documents.find(d=>d.id===docLine(b.dataset.id).documentId).type+'Id']=null;g.selected={};g.acknowledged=false;draftCheck.groups.push(newGroup(docLine(b.dataset.id)));}
  if(action==='exclude-line'){
   const id=f.elements['exclude-id'].value,reason=f.elements['exclude-reason'].value.trim();
   if(!reason)throw Error('Justifique por que o item não é pertinente.');
   if(draftCheck.lines.length-draftCheck.excluded.length<=1)throw Error('Mantenha pelo menos um item pertinente.');
   g[current.documents.find(d=>d.id===docLine(id).documentId).type+'Id']=null;g.selected={};g.acknowledged=false;draftCheck.excluded.push({id,reason});draftCheck.groups=draftCheck.groups.filter(v=>memberIds(v).length);
  }
  await saveCheck();
  if(action==='check-next'){if(productIndex<draftCheck.groups.length-1)productIndex++;else documentSummary=true;}
  if(action==='check-previous')productIndex=Math.max(0,productIndex-1);
  if(action==='check-summary')documentSummary=true;
 }
 else if(action==='check-item'){productIndex=Number(b.dataset.index);documentSummary=false;}
 else if(action==='restore-line'){draftCheck.excluded=draftCheck.excluded.filter(v=>v.id!==b.dataset.id);draftCheck.groups.push(newGroup(docLine(b.dataset.id)));productIndex=draftCheck.groups.length-1;await saveCheck();}
 else if(action==='previous-product'){draftProducts[productIndex]=readProducts(root.querySelector('[data-import-form=products]'))[0];productIndex--;}
 else if(action==='remove-product'){if(draftProducts.length===1)throw Error('Mantenha ao menos um produto. Corrija os dados ou envie outro documento para refazer a leitura.');draftProducts.splice(productIndex,1);productIndex=Math.min(productIndex,draftProducts.length-1);}
 else if(action==='list'){current=null;draftProducts=null;draftCheck=null;documentSummary=false;editingDocuments=false;productIndex=0;const u=new URL(location.href);u.searchParams.delete('importCase');history.replaceState(null,'',u);await lists();}
 else if(action==='extract'){if(current.products.length&&!confirm('Uma nova leitura substituirá sua conferência e invalidará a revisão. Continuar?'))return;await command(action);}
 else await command(action);
 });});
async function lists(){if(user&&config.storageReady){cases=(await api('/cases')).cases;if(config.reviewer)queue=(await api('/queue')).cases;}}
async function activate(){if(document.body.dataset.activePage!=='auditoria-importacao')return;await run(async()=>{const turn=epoch;const auth=await fetch('/api/auth/me').then(r=>{if(!r.ok)throw Error('Não foi possível consultar a sessão.');return r.json();});const c=await api('/config');if(turn!==epoch)return;user=auth.user;config=c;await lists();const id=new URL(location.href).searchParams.get('importCase');if(id&&user&&config.storageReady)setCase((await api('/cases/'+id)).case);},false);}
document.addEventListener('audita:pagechange',()=>{clearTimeout(timer);void activate();});
root?.addEventListener('click',e=>{const action=e.target.closest('[data-import-view]')?.dataset.importView;if(action==='open')root.querySelector('#importPrevious')?.showModal();if(action==='close')root.querySelector('#importPrevious')?.close();});
root?.addEventListener('toggle',()=>requestAnimationFrame(()=>motion.moveAssistantAvatar(root.querySelector('.charge-analysis-conversation'),{immediate:true})),true);
window.addEventListener('resize',()=>{if(root?.querySelector('.import-stage'))motion.moveAssistantAvatar(root.querySelector('.charge-analysis-conversation'),{immediate:true});});
window.addEventListener('audita:auth-changed',()=>{epoch++;busy=false;processing='';user=null;current=null;draftProducts=null;draftCheck=null;documentSummary=false;productIndex=0;editingDocuments=false;cases=[];queue=[];render();void activate();});
void activate();
