const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
let dashboard = null;
let currentUser = null;

const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const number = (value) => new Intl.NumberFormat("pt-BR").format(Number(value || 0));
const money = (value) => new Intl.NumberFormat("pt-BR", { style:"currency", currency:value?.currency || "BRL" }).format(Number(value?.cents || 0) / 100);
const date = (value) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle:"short", timeStyle:"short" }).format(new Date(value)) : "—";
const labels = {active:"Ativo",trialing:"Em teste",past_due:"Em atraso",unpaid:"Não pago",canceled:"Cancelado",suspended:"Suspenso",processed:"Processado",failed:"Falhou",processing:"Processando",owner:"Proprietário",admin:"Administrador",analyst:"Analista",member:"Membro"};
const label = (value) => labels[value] || value || "—";
const tone = (value) => ["active","trialing","processed"].includes(value) ? "positive" : ["past_due","processing"].includes(value) ? "warning" : ["suspended","unpaid","canceled","failed"].includes(value) ? "negative" : "";
const empty = (columns, message) => `<tr><td colspan="${columns}" class="empty">${message}</td></tr>`;

function showError(message) { const el = $("#dashboardError"); el.textContent = message; el.classList.toggle("hidden", !message); }
function setBusy(active) { $("#dashboardView")?.classList.toggle("busy", active); }
async function api(path, options = {}) { const response = await fetch(path, { headers:{ accept:"application/json", ...(options.body ? {"content-type":"application/json"} : {}) }, ...options }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(payload.message || payload.error || "Não foi possível concluir a operação."); error.status = response.status; throw error; } return payload; }

function accessFor(user) { if (["active","trialing"].includes(user.subscription?.status)) return {name:label(user.subscription.status),detail:`${user.subscription.planId} · ${user.subscription.interval === "annual" ? "anual" : "mensal"}`,tone:"positive"}; if (user.testerGrant?.status === "active" && (!user.testerGrant.expiresAt || new Date(user.testerGrant.expiresAt) > new Date())) return {name:"Tester",detail:"Liberação manual",tone:"positive"}; return {name:"Sem acesso",detail:"",tone:""}; }

function renderUsers() {
  const query = $("#userSearch").value.trim().toLowerCase();
  const users = (dashboard?.users || []).filter((user) => !query || [user.name,user.email,user.tenantName].some((v) => String(v||"").toLowerCase().includes(query)));
  $("#userRows").innerHTML = users.length ? users.map((user) => { const access=accessFor(user); const self=String(user.id)===String(currentUser.id); const tester=user.testerGrant?.status==="active" && access.detail==="Liberação manual"; return `<tr><td><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></td><td>${escapeHtml(user.tenantName)}</td><td><select data-user-role="${escapeHtml(user.id)}" ${self?'disabled':''}>${["owner","admin","analyst","member"].map((role)=>`<option value="${role}" ${user.role===role?'selected':''}>${label(role)}</option>`).join("")}${self?'<option selected>Super Admin</option>':''}</select></td><td><span class="badge ${access.tone}">${escapeHtml(access.name)}</span><small>${escapeHtml(access.detail)}</small></td><td><span class="badge ${tone(user.status)}">${label(user.status)}</span></td><td><div class="row-actions"><button data-access="${tester?'revoke':'grant'}" data-user="${escapeHtml(user.id)}" ${user.subscription && access.tone==='positive'?'disabled':''}>${tester?'Revogar tester':'Liberar tester'}</button><button class="${user.status==='active'?'':'primary'}" data-status="${user.status==='active'?'suspended':'active'}" data-user="${escapeHtml(user.id)}" ${self?'disabled':''}>${user.status==='active'?'Suspender':'Reativar'}</button></div></td></tr>`; }).join("") : empty(6,"Nenhum usuário encontrado.");
}

function renderSubscriptions() {
  const filter=$("#subscriptionFilter").value; const subscriptions=(dashboard?.subscriptions||[]).filter((item)=>!filter||item.status===filter);
  $("#subscriptionRows").innerHTML=subscriptions.length?subscriptions.map((item)=>`<tr><td><strong>${escapeHtml(item.tenantName)}</strong><small>${escapeHtml(item.customerEmail)}</small></td><td><strong>${escapeHtml(item.planId)}</strong><small>${item.interval==='annual'?'Anual':'Mensal'}</small></td><td><span class="badge ${tone(item.status)}">${label(item.status)}</span>${item.cancelAtPeriodEnd?'<small>Cancelamento agendado</small>':''}</td><td>${date(item.currentPeriodEnd)}</td><td>${number(item.creditBalance)}</td><td><div class="row-actions"><button data-subscription="${escapeHtml(item.tenantId)}" data-cancel="${item.cancelAtPeriodEnd?'resume':'cancel'}" ${!["active","trialing"].includes(item.status)?'disabled':''}>${item.cancelAtPeriodEnd?'Manter assinatura':'Cancelar ao fim do ciclo'}</button></div></td></tr>`).join(""):empty(6,"Nenhuma assinatura encontrada.");
}

function render() { const summary=dashboard.summary||{}; $("#metricMrr").textContent=money(summary.mrr); $("#metricActive").textContent=number(summary.activeSubscriptions); $("#metricPastDue").textContent=`${number(summary.pastDueSubscriptions)} em atraso`; $("#metricUsers").textContent=number(dashboard.users?.length); $("#metricCredits").textContent=number(summary.outstandingCredits); $("#eventRows").innerHTML=dashboard.recentEvents?.length?dashboard.recentEvents.map((event)=>`<tr><td><strong>${escapeHtml(event.type)}</strong></td><td>${escapeHtml(event.tenantName)}</td><td><span class="badge ${tone(event.status)}">${label(event.status)}</span></td><td>${date(event.processedAt||event.eventCreatedAt)}</td></tr>`).join(""):empty(4,"Nenhum evento recente."); renderUsers(); renderSubscriptions(); }
async function loadDashboard() { setBusy(true); showError(""); try { dashboard=await api("/api/super-admin/dashboard"); render(); } catch(error) { if(error.status===401||error.status===403) return showLogin(error.status===403?"Este login não possui permissão de super admin.":""); showError(error.message); } finally { setBusy(false); } }
function showLogin(message="") { $("#loginView").classList.remove("hidden"); $("#dashboardView").classList.add("hidden"); $("#loginError").textContent=message; $("#loginError").classList.toggle("hidden",!message); }
function showDashboard(user) { currentUser=user; $("#loginView").classList.add("hidden"); $("#dashboardView").classList.remove("hidden"); $("#adminName").textContent=user.name; $("#adminEmail").textContent=user.email; loadDashboard(); }
async function initialize() { try { const auth=await api("/api/auth/me"); auth.user?.role==="super_admin"?showDashboard(auth.user):showLogin(auth.user?"Este login não possui permissão de super admin.":""); } catch { showLogin(); } }

$("#loginForm").addEventListener("submit",async(event)=>{event.preventDefault(); const button=event.currentTarget.querySelector("button"); button.disabled=true; try { await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("#loginEmail").value,password:$("#loginPassword").value})}); const auth=await api("/api/auth/me"); if(auth.user?.role!=="super_admin"){await api("/api/auth/logout",{method:"POST"}); throw new Error("Este login não possui permissão de super admin.");} showDashboard(auth.user); } catch(error){showLogin(error.message==="invalid_credentials"?"E-mail ou senha inválidos.":error.message);} finally{button.disabled=false;}});
$("#logoutButton").addEventListener("click",async()=>{await api("/api/auth/logout",{method:"POST"}).catch(()=>{}); showLogin();});
$$('[data-tab]').forEach((button)=>button.addEventListener("click",()=>{$$('[data-tab]').forEach((item)=>item.classList.toggle("active",item===button));$$('[data-panel]').forEach((panel)=>panel.classList.toggle("active",panel.dataset.panel===button.dataset.tab));$("#pageTitle").textContent=button.textContent;}));
$("#userSearch").addEventListener("input",renderUsers); $("#subscriptionFilter").addEventListener("change",renderSubscriptions); $$('[data-refresh]').forEach((button)=>button.addEventListener("click",loadDashboard));
$("#userRows").addEventListener("change",async(event)=>{const id=event.target.dataset.userRole;if(!id)return;setBusy(true);try{await api(`/api/super-admin/users/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({role:event.target.value})});await loadDashboard();}catch(error){showError(error.message);await loadDashboard();}});
$("#userRows").addEventListener("click",async(event)=>{const button=event.target.closest("button[data-user]");if(!button)return;setBusy(true);try{if(button.dataset.access)await api(`/api/super-admin/users/${encodeURIComponent(button.dataset.user)}/access`,{method:"POST",body:JSON.stringify({action:button.dataset.access})});else await api(`/api/super-admin/users/${encodeURIComponent(button.dataset.user)}`,{method:"PATCH",body:JSON.stringify({status:button.dataset.status})});await loadDashboard();}catch(error){showError(error.message);setBusy(false);}});
$("#subscriptionRows").addEventListener("click",async(event)=>{const button=event.target.closest("button[data-subscription]");if(!button)return;setBusy(true);try{await api(`/api/super-admin/subscriptions/${encodeURIComponent(button.dataset.subscription)}`,{method:"POST",body:JSON.stringify({action:button.dataset.cancel})});await loadDashboard();}catch(error){showError(error.message);setBusy(false);}});
initialize();
