import {randomUUID,createHash} from 'node:crypto';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {requireIr as check,sealIr,openIr,irKey} from './ir-exemption-domain.mjs';
import {validateBill,auditBills,VERSION,STATUSES} from './energy-audit-domain.mjs';
const types=['invoice','payment','contract','response','receipt','representation'];
const formatMoney=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const safe=(v,max=2000)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
export function createEnergyService({getDb,env=process.env,extractor,now=()=>new Date()}){
 const storage=resolve(env.AUDITA_ENERGY_STORAGE_PATH||'private-documents/energy');
 const key=()=>irKey(env.AUDITA_ENERGY_ENCRYPTION_KEY||env.AUDITA_IR_ENCRYPTION_KEY);
 const seal=(k,id,v)=>sealIr(v,key(),`energy:${k}:${id}`),open=(k,id,v,b=false)=>openIr(v,key(),`energy:${k}:${id}`,b);
 const signed=a=>check(a?.user?.id&&a.tenantId,'authentication_required','Entre na sua conta.',401);
 const team=a=>['super_admin','lawyer'].includes(a?.user?.role);
 function db(){const d=getDb();check(env.AUDITA_ENERGY_ENABLED==='true'&&d.dbReady&&d.pool&&key(),'unavailable','Armazenamento seguro indisponível.',503);return d.pool;}
 async function tx(fn){const c=await db().connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async function access(c,a,id,lock=false){signed(a);const r=(await c.query(`SELECT * FROM audita_energy_cases WHERE id=$1${lock?' FOR UPDATE':''}`,[id])).rows[0];const owner=r&&String(r.user_id)===String(a.user.id)&&String(r.tenant_id)===String(a.tenantId);const operator=r&&team(a)&&(a.user.role==='super_admin'||String(r.assigned_user_id)===String(a.user.id));check(owner||operator,'not_found','Atendimento não encontrado.',404);return {r,p:open('case',id,r.encrypted_payload),owner,operator};}
 async function docs(c,id){return (await c.query('SELECT * FROM audita_energy_documents WHERE case_id=$1 ORDER BY created_at,id',[id])).rows.map(r=>({...open('doc',r.id,r.encrypted_payload),id:r.id,type:r.type,state:r.state}));}
 async function event(c,id,a,message,internal=false){const eid=randomUUID();await c.query('INSERT INTO audita_energy_events(case_id,actor_id,internal,encrypted_payload) VALUES($1,$2,$3,$4)',[id,a?.user?.id||null,internal,seal('event',id,{message,at:now().toISOString(),id:eid})]);}
 async function save(c,x){await c.query('INSERT INTO audita_energy_versions(case_id,revision,encrypted_payload) SELECT id,revision,encrypted_payload FROM audita_energy_cases WHERE id=$1 ON CONFLICT DO NOTHING',[x.r.id]);await c.query('UPDATE audita_energy_cases SET encrypted_payload=$2,status=$3,revision=revision+1,updated_at=NOW() WHERE id=$1',[x.r.id,seal('case',x.r.id,x.p),x.r.status]);}
 async function refs(c){return (await c.query('SELECT * FROM audita_energy_references')).rows;}
 async function recalc(c,x){const references=await refs(c);x.p.analysis=auditBills(await docs(c,x.r.id),references.flatMap(r=>r.payload.rows||[]));x.p.analysis.references=references.map(r=>({kind:r.kind,fetchedAt:r.fetched_at,error:r.error}));x.p.confirmation=null;x.p.request=null;if(x.r.status==='prepared')x.r.status='collecting';await save(c,x);}
 async function view(c,x){const r=(await c.query('SELECT revision FROM audita_energy_cases WHERE id=$1',[x.r.id])).rows[0];return {id:x.r.id,status:x.r.status,revision:r.revision,permissions:{owner:!!x.owner,operator:!!x.operator},...x.p,documents:await docs(c,x.r.id),events:(await c.query(`SELECT encrypted_payload FROM audita_energy_events WHERE case_id=$1 ${x.operator?'':'AND internal=FALSE'} ORDER BY id DESC LIMIT 200`,[x.r.id])).rows.map(r=>open('event',x.r.id,r.encrypted_payload))};}
 async function configuration(a){const d=getDb(),enabled=env.AUDITA_ENERGY_ENABLED==='true';return {enabled,ready:!!(enabled&&d.dbReady&&key()&&extractor?.available()),storageReady:!!(enabled&&d.dbReady&&key()),operator:team(a),version:VERSION,statuses:STATUSES};}
 async function list(a,queue=false){signed(a);if(queue)check(team(a),'forbidden','Acesso da equipe necessário.',403);return (await db().query(queue?`SELECT id,status,assigned_user_id,updated_at FROM audita_energy_cases WHERE assigned_user_id=$1 OR (queued=TRUE AND assigned_user_id IS NULL) ${a.user.role==='super_admin'?'OR queued=TRUE':''} ORDER BY updated_at DESC LIMIT 100`:'SELECT id,status,updated_at FROM audita_energy_cases WHERE user_id=$1 AND tenant_id=$2 ORDER BY updated_at DESC LIMIT 100',queue?[a.user.id]:[a.user.id,a.tenantId])).rows;}
 async function create(a,input){signed(a);check((await configuration(a)).ready,'reader_unavailable','O provedor de leitura precisa ser configurado.',503);check(input?.consent===true&&['self','representative','company'].includes(input.role),'consent_required','Confirme sua autorização e representação.');return tx(async c=>{const id=randomUUID();await c.query('INSERT INTO audita_energy_cases(id,tenant_id,user_id,encrypted_payload) VALUES($1,$2,$3,$4)',[id,a.tenantId,a.user.id,seal('case',id,{role:input.role,consentAt:now().toISOString(),analysis:null,confirmation:null,request:null,protocol:null,outcome:null,tasks:[]})]);const x=await access(c,a,id);await event(c,id,a,'Atendimento iniciado com autorização.');return view(c,x);});}
 async function get(a,id){return tx(async c=>{const x=await access(c,a,id,true);await event(c,id,a,'Acesso ao caso.',true);return view(c,x);});}
 async function upload(a,id,{buffer,name,type}){check(types.includes(type)&&Buffer.isBuffer(buffer)&&buffer.length>0&&buffer.length<=10*1024*1024,'invalid_file','Envie PDF, PNG ou JPEG de até 10 MB.');const mime=buffer.subarray(0,5).toString()==='%PDF-'?'application/pdf':buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':buffer[0]===255&&buffer[1]===216?'image/jpeg':null;check(mime,'invalid_file','Formato não reconhecido.');return tx(async c=>{const x=await access(c,a,id,true);check(type!=='invoice'||!x.p.protocol,'already_presented','Após protocolar, acompanhe a resposta neste caso. Novas faturas exigem outro atendimento.',409);const hash=createHash('sha256').update(buffer).digest('hex');if((await c.query('SELECT id FROM audita_energy_documents WHERE case_id=$1 AND hash=$2',[id,hash])).rows.length)return view(c,x);const did=randomUUID();await mkdir(storage,{recursive:true,mode:0o700});await writeFile(join(storage,did),seal('file',did,buffer),{mode:0o600,flag:'wx'});const state=['invoice','response'].includes(type)?'queued':'ready';await c.query('INSERT INTO audita_energy_documents(id,case_id,hash,type,state,encrypted_payload) VALUES($1,$2,$3,$4,$5,$6)',[did,id,hash,type,state,seal('doc',did,{name:String(name||'documento').slice(0,150),mime,bill:null,error:null})]);if(state==='queued')await c.query('INSERT INTO audita_energy_jobs(id,document_id) VALUES($1,$2)',[randomUUID(),did]);await event(c,id,a,'Documento recebido.');if(type==='invoice')await recalc(c,x);else await save(c,x);return view(c,x);});}
 async function download(a,id,did){return tx(async c=>{await access(c,a,id);const d=(await docs(c,id)).find(x=>x.id===did);check(d,'not_found','Documento não encontrado.',404);await event(c,id,a,'Acesso a documento.',true);return {...d,buffer:open('file',did,await readFile(join(storage,did),'utf8'),true)};});}
 async function claim(a,id){signed(a);check(team(a),'forbidden','Acesso da equipe necessário.',403);return tx(async c=>{const r=await c.query('UPDATE audita_energy_cases SET assigned_user_id=$2 WHERE id=$1 AND queued=TRUE AND assigned_user_id IS NULL RETURNING id',[id,a.user.id]);check(r.rows.length,'conflict','Atendimento já atribuído.',409);const x=await access(c,a,id);await event(c,id,a,'Equipe assumiu o atendimento.');return view(c,x);});}
 async function command(a,id,i){return tx(async c=>{const x=await access(c,a,id,true),p=x.p;check(i?.revision===x.r.revision,'conflict','Atendimento atualizado. Recarregue.',409);const files=await docs(c,id);const evidence=(did,type)=>files.some(d=>d.id===did&&d.type===type);let message='Atendimento atualizado.';
 if(['correct','supersede'].includes(i.action))check(!p.protocol,'already_presented','Faturas já protocoladas não podem ser alteradas.',409);
 if(i.action==='correct'){
  check(x.owner,'forbidden','Somente o solicitante confirma os dados.',403);const d=files.find(d=>d.id===i.documentId&&d.type==='invoice');check(d,'not_found','Fatura não encontrada.',404);check(d.state!=='queued'&&d.state!=='reading','busy','Aguarde a leitura terminar.',409);
  let bill;try{bill=validateBill(i.bill);}catch{check(false,'invalid_bill','Revise os campos da fatura.');}
  check(!bill.paymentDocumentId||evidence(bill.paymentDocumentId,'payment'),'evidence_required','Comprovante de pagamento inválido.');check(!bill.contract||evidence(bill.contract.documentId,'contract'),'evidence_required','Anexe o contrato.');
  await c.query('INSERT INTO audita_energy_document_versions(document_id,encrypted_payload) SELECT id,encrypted_payload FROM audita_energy_documents WHERE id=$1',[d.id]);
  await c.query("UPDATE audita_energy_documents SET encrypted_payload=$2,state='ready' WHERE id=$1",[d.id,seal('doc',d.id,{...d,bill,error:null})]);await recalc(c,x);message='Dados corrigidos; análise recalculada e pedido anterior invalidado.';
 }else if(i.action==='supersede'){
  check(x.owner,'forbidden','Confirmação do solicitante necessária.',403);const d=files.find(d=>d.id===i.documentId&&d.type==='invoice'),replacement=files.find(d=>d.id===i.replacementId&&d.type==='invoice');check(d&&replacement&&d.id!==replacement.id&&!replacement.supersededBy,'invalid_replacement','Selecione a fatura válida.');await c.query('UPDATE audita_energy_documents SET encrypted_payload=$2 WHERE id=$1',[d.id,seal('doc',d.id,{...d,supersededBy:replacement.id})]);await recalc(c,x);message='Segunda via ou retificação identificada.';
 }else if(i.action==='confirm'){
  check(x.owner&&i.confirmed===true,'confirmation_required','Confirme o resumo.',403);check(p.analysis&&files.some(d=>d.bill&&!d.supersededBy)&&!files.some(d=>['queued','reading'].includes(d.state)),'analysis_required','Aguarde a análise.');check(!p.analysis.pending.length,'missing_data','Complete dados pendentes antes de preparar o pedido.');
  check(safe(i.holder,250)&&safe(i.channel,500),'missing_data','Confirme titular e canal oficial conforme a fatura.');check(p.role==='self'||files.some(d=>d.type==='representation'),'representation_required','Anexe autorização de representação.');p.confirmation={at:now().toISOString(),by:a.user.id,holder:i.holder,channel:i.channel,revision:x.r.revision};message='Resumo confirmado pelo solicitante.';
 }else if(i.action==='prepare'){
  check(x.owner&&p.confirmation&&!p.protocol,'confirmation_required','Confirme o resumo antes de gerar o pedido.');p.request={id:randomUUID(),version:VERSION,at:now().toISOString(),analysis:p.analysis,confirmation:p.confirmation};x.r.status='prepared';message='Pedido preparado; ainda não apresentado à distribuidora.';
 }else if(i.action==='protocol'){
  check(['prepared','protocol'].includes(x.r.status)&&p.request&&safe(i.number,100)&&/^\d{4}-\d{2}-\d{2}$/.test(i.date)&&!isNaN(Date.parse(i.date))&&new Date(i.date).toISOString().slice(0,10)===i.date&&i.date<=now().toISOString().slice(0,10),'invalid_protocol','Informe número e data válida do protocolo.');p.protocol={number:i.number,date:i.date,by:a.user.id};x.r.status='protocol';message='Protocolo informado pelo usuário; envio externo não realizado pela Audita.';
 }else if(i.action==='status'){
  const allowed={protocol:['pending','response'],pending:['response'],response:['pending','approved','denied','closed'],denied:['pending','closed'],approved:['received','closed'],received:['closed']};check(allowed[x.r.status]?.includes(i.status),'invalid_transition','Transição indisponível.');
  if(['response','approved','denied','closed'].includes(i.status))check(evidence(i.documentId,'response'),'evidence_required','Anexe a resposta oficial.');
  if(i.status==='received')check(evidence(i.documentId,'receipt')&&['credit','deposit'].includes(i.method)&&Number.isSafeInteger(i.amountCents)&&i.amountCents>0,'evidence_required','Informe comprovante, forma e valor recebido.');
  check(i.confirmed===true&&safe(i.note),'confirmation_required','Confirme a classificação da resposta.');p.outcome={status:i.status,note:i.note,documentId:i.documentId,method:i.method||null,amountCents:i.amountCents||null,by:a.user.id};x.r.status=i.status;message=i.note;
 }else if(i.action==='reanalyze'){check(!p.protocol,'already_presented','Caso já protocolado.',409);await recalc(c,x);message='Conferência atualizada com referências disponíveis.';
 }else if(i.action==='refer'){await c.query('UPDATE audita_energy_cases SET queued=TRUE WHERE id=$1',[id]);message='Exceção encaminhada à equipe.';
 }else if(i.action==='note'){check(safe(i.text)&&(!i.internal||x.operator),'invalid_note','Nota inválida ou sem permissão.');message=i.text;
 }else if(i.action==='task'){check(x.operator&&safe(i.title,250),'forbidden','Ação da equipe.',403);check(!i.dueDate||(/^\d{4}-\d{2}-\d{2}$/.test(i.dueDate)&&!isNaN(Date.parse(i.dueDate))&&new Date(i.dueDate).toISOString().slice(0,10)===i.dueDate),'invalid_date','Prazo inválido.');p.tasks.push({id:randomUUID(),title:i.title,dueDate:i.dueDate||null,done:false});message='Tarefa registrada.';
 }else if(i.action==='task_done'){check(x.operator,'forbidden','Ação da equipe.',403);const t=p.tasks.find(t=>t.id===i.taskId);check(t,'not_found','Tarefa não encontrada.');t.done=i.done===true;message='Tarefa atualizada.';
 }else check(false,'invalid_action','Ação inválida.');
 await save(c,x);await event(c,id,a,message,i.action==='note'&&i.internal===true);return view(c,x);});}
 async function generate(a,id){return tx(async c=>{const x=await access(c,a,id,true);check(x.p.request&&x.p.confirmation,'confirmation_required','Prepare o pedido após confirmar os dados.');const files=await docs(c,id);const paid=files.filter(d=>d.bill?.paid&&d.bill.paymentDocumentId&&files.some(f=>f.id===d.bill.paymentDocumentId&&f.type==='payment'));const lines=['PEDIDO DE ESCLARECIMENTO E REVISÃO DE FATURAMENTO',`Referência Audita: ${id} | Modelo ${VERSION}`,`Titular/solicitante: ${x.p.confirmation.holder}`,`Canal confirmado pelo cliente: ${x.p.confirmation.channel}`,'Solicito esclarecimentos e revisão dos itens abaixo, com memória de cálculo e documentação anexa.',paid.length?'Para os valores comprovadamente pagos a maior, solicito análise da devolução cabível.':'O presente pedido não comprova pagamento nem aprovação de restituição.',...x.p.analysis.findings.map(f=>`${f.unit} ${f.month} | Documento ${f.documentId} página ${f.page??'não identificada'} | ${f.label}: cobrado ${f.monetary?formatMoney(f.actual):f.actual+' kWh'}, referência ${f.monetary?formatMoney(f.expected):f.expected+' kWh'}, diferença ${f.monetary?formatMoney(f.delta):f.delta+' kWh'}. Cálculo: ${f.calculation}. Fonte: ${f.reference}`),...x.p.analysis.checks.filter(f=>f.state==='not_checked').map(f=>`Não conferido: ${f.label} - ${f.reason}`),'Anexos:',...files.map(f=>`${f.id}: ${f.name}`),x.p.analysis.notice,'Documento preparado para conferência e apresentação pelo cliente. Não protocolado.','Assinatura: __________________________________'];const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage(),y=790;for(const raw of lines){let line='';for(const word of raw.replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[^\x20-\x7e\xa0-\xff]/g,'?').split(/\s+/).flatMap(word=>word.match(/.{1,55}/g)||[])){if(font.widthOfTextAtSize(line+' '+word,9)>490){if(y<45){page=pdf.addPage();y=790;}page.drawText(line,{x:45,y,size:9,font});y-=14;line=word;}else line+=(line?' ':'')+word;}if(y<45){page=pdf.addPage();y=790;}page.drawText(line,{x:45,y,size:9,font});y-=20;}await event(c,id,a,'Download do requerimento.',true);return {buffer:Buffer.from(await pdf.save()),name:'pedido-contas-de-luz.pdf',mime:'application/pdf'};});}
 async function runJobs(){
  const expired=(await db().query("SELECT j.id,d.case_id,d.type,c.user_id,c.tenant_id FROM audita_energy_jobs j JOIN audita_energy_documents d ON d.id=j.document_id JOIN audita_energy_cases c ON c.id=d.case_id WHERE j.state='running' AND j.attempts>=3 AND j.lease_until<NOW()")).rows;
  for(const e of expired)await tx(async c=>{const x=await access(c,{user:{id:e.user_id},tenantId:e.tenant_id},e.case_id,true);const r=await c.query("UPDATE audita_energy_jobs SET state='failed',error='retry_limit',lease_until=NULL WHERE id=$1 AND state='running' AND lease_until<NOW() RETURNING document_id",[e.id]);if(!r.rows.length)return;await c.query("UPDATE audita_energy_documents SET state='needs_correction' WHERE id=$1",[r.rows[0].document_id]);if(e.type==='invoice')await recalc(c,x);else await save(c,x);await event(c,e.case_id,null,'Leitura interrompida após três tentativas. Correção necessária.');});
  const jobs=await tx(async c=>(await c.query("UPDATE audita_energy_jobs SET state='running',lease_until=NOW()+INTERVAL '3 minutes',attempts=attempts+1 WHERE id IN (SELECT id FROM audita_energy_jobs WHERE attempts<3 AND run_at<=NOW() AND (state='queued' OR (state='running' AND lease_until<NOW())) ORDER BY run_at FOR UPDATE SKIP LOCKED LIMIT 2) RETURNING *")).rows);
  for(const j of jobs){let d,auth,cid;
   try{const row=(await db().query('SELECT d.*,c.user_id,c.tenant_id FROM audita_energy_documents d JOIN audita_energy_cases c ON c.id=d.case_id WHERE d.id=$1',[j.document_id])).rows[0];cid=row.case_id;auth={tenantId:row.tenant_id,user:{id:row.user_id}};d={...open('doc',row.id,row.encrypted_payload),type:row.type};await db().query("UPDATE audita_energy_documents SET state='reading' WHERE id=$1",[row.id]);const result=await extractor({...d,type:row.type,buffer:open('file',row.id,await readFile(join(storage,row.id),'utf8'),true)},auth);
    await tx(async c=>{const x=await access(c,auth,cid,true);const lease=await c.query("SELECT id FROM audita_energy_jobs WHERE id=$1 AND state='running' AND attempts=$2 FOR UPDATE",[j.id,j.attempts]);if(!lease.rows.length)return;const fresh=open('doc',row.id,(await c.query('SELECT encrypted_payload FROM audita_energy_documents WHERE id=$1',[row.id])).rows[0].encrypted_payload);const value=row.type==='invoice'?{bill:validateBill(result),error:null}:{responseSummary:String(result.summary||'Sem resumo disponível').slice(0,3000),suggestedStatus:result.suggestedStatus||null};await c.query("UPDATE audita_energy_documents SET state=$3,encrypted_payload=$2 WHERE id=$1",[row.id,seal('doc',row.id,{...fresh,...value}),row.type==='invoice'&&['unit','distributor','month','totalCents'].some(k=>value.bill[k]===null)?'needs_correction':'ready']);await c.query("UPDATE audita_energy_jobs SET state='done',lease_until=NULL WHERE id=$1",[j.id]);if(row.type==='invoice')await recalc(c,x);else await save(c,x);await event(c,cid,null,'Leitura e análise atualizadas.');});
   }catch(e){const transient=e.code==='ai_unavailable',state=transient&&j.attempts<3?'queued':'failed';if(d&&cid)await tx(async c=>{const x=await access(c,auth,cid,true);const r=await c.query("UPDATE audita_energy_jobs SET state=$2,lease_until=NULL,run_at=NOW()+INTERVAL '1 minute',error=$3 WHERE id=$1 AND state='running' AND attempts=$4 RETURNING id",[j.id,state,transient?'reader_unavailable':'document_needs_review',j.attempts]);if(!r.rows.length)return;await c.query('UPDATE audita_energy_documents SET state=$2,encrypted_payload=$3 WHERE id=$1',[j.document_id,state==='queued'?'queued':'needs_correction',seal('doc',j.document_id,{...d,error:e.code==='split_invoices'?'Separe as faturas em arquivos individuais.':'Não foi possível concluir a leitura. Reenvie ou corrija os campos.'})]);if(d.type==='response')await save(c,x);else await recalc(c,x);});}

  }
 }
 return {configuration,list,create,get,upload,download,claim,command,generate,runJobs};
}
